stages:
  - test
  - build

variables:
  MAVEN_IMAGE: "maven:3.9-eclipse-temurin-25"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/

.before_maven:
  image: $MAVEN_IMAGE
  before_script:
    - java -version
    - mvn -version

test_dataprocessor:
  extends: .before_maven
  stage: test
  script:
    - cd "Data Processor"
    - mvn clean test

test_api_service:
  extends: .before_maven
  stage: test
  script:
    - cd api-service
    - mvn clean test -DskipTests

build_dataprocessor:
  extends: .before_maven
  stage: build
  script:
    - cd "Data Processor"
    - mvn clean package -DskipTests
    - ls -lh target/*.jar

build_api_service:
  extends: .before_maven
  stage: build
  script:
    - cd api-service
    - mvn clean package -DskipTests
    - ls -lh target/*.jar