#!/usr/bin/env python3
"""
JSON-driven Kafka audit-trail simulator.

This simulator uses:
- backend-apis-actions.json: authoritative mapping from backend API to tracked audit action
- actions_order-v2.json: authoritative frontend navigation / auth flow / route graph

Normal sessions follow the navigation contract as closely as possible using the
tracked actions resolved from those two JSON files. Anomalies are generated by
starting from valid contract-compliant journeys and then perturbing them.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
import time
import uuid
from collections import Counter, deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Deque, Dict, Iterable, List, Optional, Sequence, Tuple

try:
    from kafka import KafkaProducer
except Exception:
    KafkaProducer = None

DEFAULT_BACKEND_APIS = Path(__file__).with_name("backend-apis-actions.json")
DEFAULT_ACTIONS_ORDER = Path(__file__).with_name("actions_order-v2.json")

# Full label set provided by the user / training taxonomy.
ANOMALY_TYPES = [
    "data_exfiltration",
    "distributed_brute_force",
    "geo_jump",
    "impossible_device_switch",
    "impossible_seq",
    "ping_pong_loop",
    "rapid_fire",
    "repeated_fail",
    "skip_login",
    "unusual_hour",
    "zombie_session",
]

DOWNLOAD_KEYWORDS = (
    "download", "télécharg", "export", "wallet", "certificate", "tp-card", "refund-resume", "adhesion-certificate"
)

PERSONAS = ["self_service", "frequent_checker", "admin_delegated"]
ENVIRONMENTS = ["10", "11"]
COMPANY_IDS = [27011, 27012, 27013, 27021]
COMPANY_GROUP_IDS = [12001, 12002, 12003]
INSURER_IDS = [1, 2, 3]
COMPANY_SECTION_IDS = [110027, 110028, 110029]
INSURER_CODE_IDS = [302, 303, 304]
HEALTHCARE_NETWORK_IDS = [1, 2, 3]
DOMAIN_IDS = [10, 11, 12]

GEO_PROFILE = {
    "FR": {"cities": ["Paris", "Lyon", "Lille", "Toulouse", "Nantes", "Bordeaux", "Strasbourg", "Marseille"], "prefixes": [("81", "64"), ("82", "64"), ("86", "192"), ("90",), ("2",)], "weight": 0.72},
    "BE": {"cities": ["Brussels", "Antwerp", "Ghent", "Liège"], "prefixes": [("37", "60"), ("46", "18")], "weight": 0.08},
    "DE": {"cities": ["Berlin", "Hamburg", "Munich", "Frankfurt"], "prefixes": [("46", "5"), ("87", "123")], "weight": 0.08},
    "ES": {"cities": ["Madrid", "Barcelona", "Valencia"], "prefixes": [("80", "58"), ("81", "32")], "weight": 0.06},
    "IT": {"cities": ["Milan", "Rome", "Turin"], "prefixes": [("79", "0"), ("82", "48")], "weight": 0.06},
}

DEVICE_POOL = [
    ("WEB", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/123.0.0.0 Safari/537.36"),
    ("WEB", "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15 Version/17.4 Safari/605.1.15"),
    ("MOBILE_ANDROID", "mobileapp/4.2.1 (android; sdk=34; locale=fr-FR)"),
    ("MOBILE_ANDROID", "mobileapp/4.1.7 (android; sdk=33; locale=fr-FR)"),
    ("MOBILE_IOS", "mobileapp/4.3.0 (ios; build=812; locale=fr-FR)"),
]

ROUTE_CANONICAL = {
    "Home": "home",
    "Requests": "requests",
    "Refunds": "refunds",
    "Documents": "documents",
    "Beneficiaries": "beneficiaries",
    "UpdateBeneficiaries": "beneficiaries",
    "PersonalInformation": "personal_info",
    "BankingInformation": "banking_info",
    "GlobalPreferences": "preferences",
    "Help": "help",
    "TpCardDownload": "tp_card",
    "ValidateLegalPages": "validate_legal_pages",
    "ValidateInfoDialog": "validate_info_dialog",
    "login": "login",
    "mfa": "mfa",
    "mfa_email_list": "mfa_email_list",
    "logout": "logout",
    "home": "home",
    "requests": "requests",
    "refunds": "refunds",
    "documents": "documents",
    "beneficiaries": "beneficiaries",
    "personal_info": "personal_info",
    "banking_info": "banking_info",
    "preferences": "preferences",
    "help": "help",
    "logout": "logout",
}

@dataclass(frozen=True)
class ActionSpec:
    action: str
    type_name: str
    sub_type: Optional[str]
    route: str
    api: str
    route_name: str
    action_name: Optional[str] = None
    is_download: bool = False

@dataclass
class UserProfile:
    insured_id: str
    persona: str
    country_code: str
    city: str
    device: str
    user_agent: str
    ip: str
    company_id: int
    company_group_id: int
    insurer_id: int
    company_section_id: int
    insurer_code_id: int
    healthcare_network_id: int
    domain_id: int
    environment_id: str
    session_counter: int = 0

@dataclass
class EventPlan:
    spec: ActionSpec
    created_at: datetime
    route: str
    state: str
    force_status: Optional[str] = None
    force_http_code: Optional[int] = None
    force_ip: Optional[str] = None
    force_device: Optional[str] = None
    force_user_agent: Optional[str] = None
    campaign_id: Optional[str] = None
    metadata: Dict[str, object] = field(default_factory=dict)

class Catalog:
    def __init__(self) -> None:
        self.api_to_action: Dict[str, Dict] = {}
        self.route_actions: Dict[str, List[ActionSpec]] = {}
        self.auth_variants: Dict[str, List[List[ActionSpec]]] = {}
        self.transition_edges: Dict[str, List[str]] = {}
        self.logout_actions: List[ActionSpec] = []
        self.global_navigation_apis: List[str] = []
        self.untracked_api_count: int = 0
        self.tracked_api_count: int = 0

    def resolve(self, api_ref: str, route_name: str, action_name: Optional[str]) -> List[ActionSpec]:
        matches = []
        method, path = split_api(api_ref)
        norm_target = normalize_path(path)
        prefix_target = wildcard_prefix(path)
        for key, payload in self.api_to_action.items():
            kmethod, kpath = split_api(key)
            if kmethod != method:
                continue
            if path == kpath or norm_target == normalize_path(kpath):
                matches.append(make_spec(payload, route_name, action_name, api_ref))
                continue
            if prefix_target and kpath.startswith(prefix_target):
                matches.append(make_spec(payload, route_name, action_name, api_ref))
        # dedupe by action + subtype + route
        out = []
        seen = set()
        for spec in matches:
            key = (spec.action, spec.sub_type, spec.route, spec.api)
            if key in seen:
                continue
            seen.add(key)
            out.append(spec)
        return out


def split_api(api_ref: str) -> Tuple[str, str]:
    text = (api_ref or "").strip()
    if " " not in text:
        return ("GET", text)
    method, path = text.split(" ", 1)
    return method.strip().upper(), path.strip()


def normalize_path(path: str) -> str:
    # make /x/{a}/y and /x/{b}/y equivalent
    return re.sub(r"\{[^/]+\}", "{}", path or "")


def wildcard_prefix(path: str) -> Optional[str]:
    if "*" in (path or ""):
        return path.split("*", 1)[0]
    return None


def clean_type(type_name: Optional[str]) -> str:
    raw = type_name or "UNKNOWN"
    return raw.split(".")[-1]


def is_downloadish(api_ref: str, action_value: str, sub_type: Optional[str], action_name: Optional[str]) -> bool:
    hay = " | ".join(filter(None, [api_ref, action_value, sub_type, action_name])).lower()
    return any(token in hay for token in DOWNLOAD_KEYWORDS)


def make_spec(payload: Dict, route_name: str, action_name: Optional[str], api_ref: str) -> ActionSpec:
    tracking = payload["actionTracking"]
    return ActionSpec(
        action=tracking["value"],
        type_name=clean_type(tracking.get("type")),
        sub_type=tracking.get("subType"),
        route=ROUTE_CANONICAL.get(route_name, route_name.lower()),
        api=api_ref,
        route_name=route_name,
        action_name=action_name,
        is_download=is_downloadish(api_ref, tracking["value"], tracking.get("subType"), action_name),
    )


def load_catalog(backend_apis_path: str, actions_order_path: str) -> Catalog:
    catalog = Catalog()
    backend_rows = json.loads(Path(backend_apis_path).read_text(encoding="utf-8"))
    order_doc = json.loads(Path(actions_order_path).read_text(encoding="utf-8"))

    for row in backend_rows:
        method = (row.get("method") or "GET").upper()
        path = row.get("path") or ""
        tracking = row.get("actionTracking")
        api_ref = f"{method} {path}"
        if tracking:
            catalog.api_to_action[api_ref] = row
            catalog.tracked_api_count += 1
        else:
            catalog.untracked_api_count += 1

    catalog.global_navigation_apis = list(order_doc.get("global", {}).get("on_every_navigation", []))

    # Auth flow variants grounded in the contract
    auth_steps = order_doc.get("auth_flow", {}).get("steps", [])
    by_state_action = {(step.get("state"), step.get("action")): step for step in auth_steps}

    def resolve_auth(state: str, action_name: str) -> List[ActionSpec]:
        step = by_state_action.get((state, action_name))
        if not step:
            return []
        specs: List[ActionSpec] = []
        for api in step.get("api", []):
            specs.extend(catalog.resolve(api, state, action_name))
        return specs

    # Direct login / MFA / SSO / derogatory flows
    submit_specs = resolve_auth("login", "submit_credentials")
    select_specs = resolve_auth("mfa_email_list", "select_email")
    validate_specs = resolve_auth("mfa", "validate_code")
    regen_specs = resolve_auth("mfa", "resend_or_switch")
    sso_specs = catalog.resolve("GET /auth/sso", "login", "sso")
    derog_specs = catalog.resolve("GET /auth/sso/derogatory", "login", "derogatory")
    logout_specs = catalog.resolve("GET /auth/logout", "logout", "explicit_logout") + catalog.resolve("GET /auth/sso/disconnect", "logout", "explicit_logout")
    catalog.logout_actions = logout_specs

    if submit_specs:
        catalog.auth_variants["direct"] = [[submit_specs[0]]]
    if submit_specs and validate_specs:
        catalog.auth_variants["mfa"] = [[submit_specs[0], validate_specs[0]]]
    if submit_specs and select_specs and validate_specs:
        catalog.auth_variants["mfa_email"] = [[submit_specs[0], select_specs[0], validate_specs[0]]]
    if submit_specs and regen_specs and validate_specs:
        catalog.auth_variants["mfa_regen"] = [[submit_specs[0], regen_specs[0], validate_specs[0]]]
    if sso_specs:
        catalog.auth_variants["sso"] = [[sso_specs[0]]]
    if derog_specs:
        catalog.auth_variants["derogatory"] = [[derog_specs[0]]]

    # Post-login gates and route actions
    for route_name, route_block in (order_doc.get("routes") or {}).items():
        specs: List[ActionSpec] = []
        for action in route_block.get("user_actions", []):
            action_name = action.get("name")
            for api in action.get("api", []):
                specs.extend(catalog.resolve(api, route_name, action_name))
        # preserve order but dedupe
        unique: List[ActionSpec] = []
        seen = set()
        for spec in specs:
            key = (spec.action, spec.sub_type, spec.api)
            if key in seen:
                continue
            seen.add(key)
            unique.append(spec)
        canonical = ROUTE_CANONICAL.get(route_name, route_name.lower())
        catalog.route_actions[canonical] = unique

    for gate_name, gate_block in (order_doc.get("post_login_gates") or {}).items():
        route_name = gate_block.get("route") or gate_name
        canonical = ROUTE_CANONICAL.get(route_name, route_name.lower())
        specs: List[ActionSpec] = []
        if gate_block.get("action"):
            for api in gate_block.get("api", []):
                specs.extend(catalog.resolve(api, route_name, gate_block.get("action")))
        for action in gate_block.get("actions", []):
            for api in action.get("api", []):
                specs.extend(catalog.resolve(api, route_name, action.get("name")))
        if specs:
            catalog.route_actions[canonical] = specs

    # Transition edges from graph
    for edge in (order_doc.get("transition_graph") or {}).get("edges", []):
        source = ROUTE_CANONICAL.get(edge.get("from"), edge.get("from"))
        target = ROUTE_CANONICAL.get(edge.get("to"), edge.get("to"))
        catalog.transition_edges.setdefault(source, []).append(target)

    # make pages navigable back to home because actual frontend tabs imply it, while graph only lists home->section edges.
    for route in list(catalog.route_actions.keys()):
        if route not in {"home", "logout", "login", "mfa", "mfa_email_list"}:
            catalog.transition_edges.setdefault(route, []).append("home")
            catalog.transition_edges.setdefault(route, []).append("logout")
    catalog.transition_edges.setdefault("home", []).append("logout")
    return catalog


def weighted_choice(items: Sequence[Tuple[object, float]], rng: random.Random):
    total = sum(weight for _, weight in items)
    pick = rng.random() * total
    upto = 0.0
    for item, weight in items:
        upto += weight
        if upto >= pick:
            return item
    return items[-1][0]


def random_public_ip(prefix: Sequence[str], rng: random.Random) -> str:
    parts = [int(x) for x in prefix]
    while len(parts) < 4:
        parts.append(rng.randint(2, 250) if len(parts) == 3 else rng.randint(0, 255))
    if parts[0] in {10, 127, 169, 172, 192}:
        parts[0] = rng.choice([2, 37, 46, 62, 77, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 93, 95])
    return ".".join(str(p) for p in parts[:4])


def parse_iso_dt(value: str) -> datetime:
    dt = datetime.fromisoformat(value)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def iso_z(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def choose_status(route: str, rng: random.Random) -> str:
    failure_rates = {
        "login": 0.03,
        "mfa": 0.04,
        "logout": 0.01,
        "requests": 0.05,
        "refunds": 0.02,
        "documents": 0.05,
        "beneficiaries": 0.05,
        "personal_info": 0.03,
        "banking_info": 0.07,
        "preferences": 0.04,
        "help": 0.02,
        "tp_card": 0.02,
    }
    return "KO" if rng.random() < failure_rates.get(route, 0.04) else "OK"


def choose_http_code(status: str, route: str, action: str, rng: random.Random) -> int:
    if status == "OK":
        if route in {"login", "mfa"}:
            return rng.choice([200, 202, 204, 206])
        if route in {"documents", "requests", "banking_info", "beneficiaries"}:
            return rng.choice([200, 201, 202])
        return rng.choice([200, 204])
    failure_codes = {
        "login": [401, 403],
        "mfa": [401, 403],
        "logout": [401],
        "banking_info": [400, 409, 422],
        "requests": [400, 422],
        "documents": [400, 422],
        "refunds": [400, 403, 422],
    }
    return rng.choice(failure_codes.get(route, [400, 403, 409, 422, 500]))


def build_request_data(spec: ActionSpec, user: UserProfile, rng: random.Random, metadata: Optional[Dict[str, object]] = None) -> Dict[str, object]:
    method, path = split_api(spec.api)
    payload: Dict[str, object] = {
        "apiMethod": method,
        "apiPath": path,
        "insuredId": user.insured_id,
        "route": spec.route,
        "action": spec.action,
    }
    if spec.route in {"login", "mfa", "mfa_email_list"}:
        payload.update({
            "login": user.insured_id,
            "channel": "mobile" if user.device.startswith("MOBILE") else "web",
            "country": user.country_code,
        })
    if spec.route == "banking_info":
        payload.update({"iban_last4": str(rng.randint(1000, 9999)), "bic": rng.choice(["AGRIFRPP", "BNPAFRPP", "SOGEFRPP", "CMCIFRPP"])})
    if spec.route in {"documents", "refunds", "tp_card"}:
        payload.update({"documentType": rng.choice(["pdf", "csv", "image"]), "exportFormat": rng.choice(["pdf", "csv"] )})
    if spec.route == "requests":
        payload.update({"priority": rng.choice(["low", "normal", "high"]), "subject": spec.action})
    if metadata:
        payload.update(metadata)
    return payload


def build_request_return(status: str, http_code: int, rng: random.Random) -> Dict[str, object]:
    if status == "OK":
        return {"status": "success", "reference": f"REF-{rng.randint(100000, 999999)}"}
    code = "VALIDATION_ERROR" if http_code in {400, 409, 422} else "ACCESS_DENIED"
    if http_code >= 500:
        code = "SERVER_ERROR"
    return {"status": "error", "code": code}


def is_login_action(action: str) -> bool:
    return action in {"Connexion", "Connexion SSO", "Connexion en tant que", "Validation MFA", "Sélection email MFA", "Régénération code MFA", "Activation de compte", "Création de compte"}


def compute_ping_pong(actions: Sequence[str]) -> int:
    count = 0
    for i in range(3, len(actions)):
        if actions[i] == actions[i - 2] and actions[i - 1] == actions[i - 3] and actions[i] != actions[i - 1]:
            count += 1
    return count


def compute_risk_score(ip_changed: int, device_changed: int, cumulative_kos: int, downloads_last_2m: int, ping_pong_count: int, unusual_hour: bool, skip_login: bool, rapid_fire_flag: bool) -> float:
    score = 0.0
    score += 30.0 * ip_changed
    score += 25.0 * device_changed
    score += 15.0 if cumulative_kos >= 3 else 0.0
    score += 15.0 if downloads_last_2m >= 10 else 0.0
    score += 15.0 if ping_pong_count >= 2 else 0.0
    score += 10.0 if unusual_hour else 0.0
    score += 10.0 if skip_login else 0.0
    score += 10.0 if rapid_fire_flag else 0.0
    return max(0.0, min(100.0, score))


def build_users(rng: random.Random, count: int) -> List[UserProfile]:
    geo_items = [(country, data["weight"]) for country, data in GEO_PROFILE.items()]
    users: List[UserProfile] = []
    for _ in range(count):
        country_code = weighted_choice(geo_items, rng)
        geo = GEO_PROFILE[country_code]
        device, user_agent = rng.choice(DEVICE_POOL)
        prefix = rng.choice(geo["prefixes"])
        users.append(UserProfile(
            insured_id=str(rng.randint(10000000, 99999999)),
            persona=rng.choice(PERSONAS),
            country_code=country_code,
            city=rng.choice(geo["cities"]),
            device=device,
            user_agent=user_agent,
            ip=random_public_ip(prefix, rng),
            company_id=rng.choice(COMPANY_IDS),
            company_group_id=rng.choice(COMPANY_GROUP_IDS),
            insurer_id=rng.choice(INSURER_IDS),
            company_section_id=rng.choice(COMPANY_SECTION_IDS),
            insurer_code_id=rng.choice(INSURER_CODE_IDS),
            healthcare_network_id=rng.choice(HEALTHCARE_NETWORK_IDS),
            domain_id=rng.choice(DOMAIN_IDS),
            environment_id=rng.choice(ENVIRONMENTS),
        ))
    return users


def route_weights_for_catalog(catalog: Catalog) -> List[Tuple[str, float]]:
    defaults = {
        "home": 0.14,
        "requests": 0.12,
        "refunds": 0.18,
        "documents": 0.16,
        "beneficiaries": 0.12,
        "personal_info": 0.08,
        "banking_info": 0.07,
        "preferences": 0.07,
        "help": 0.03,
        "tp_card": 0.03,
        "validate_legal_pages": 0.01,
        "validate_info_dialog": 0.01,
    }
    weights: List[Tuple[str, float]] = []
    for route, actions in catalog.route_actions.items():
        if route in {"login", "mfa", "mfa_email_list", "logout"} or not actions:
            continue
        weights.append((route, defaults.get(route, 0.02)))
    return weights or [("refunds", 1.0)]


def choose_auth_variant(catalog: Catalog, rng: random.Random) -> List[ActionSpec]:
    available = []
    weight_by_name = {"direct": 0.50, "mfa": 0.18, "mfa_email": 0.10, "mfa_regen": 0.04, "sso": 0.14, "derogatory": 0.04}
    for name, variants in catalog.auth_variants.items():
        if variants:
            available.append((variants[0], weight_by_name.get(name, 0.05)))
    return list(weighted_choice(available, rng))


def choose_logout(catalog: Catalog, auth_specs: Sequence[ActionSpec], rng: random.Random) -> ActionSpec:
    if not catalog.logout_actions:
        raise RuntimeError("No tracked logout action resolved from backend/action-order JSON")
    first_action = auth_specs[0].action if auth_specs else ""
    if first_action in {"Connexion SSO", "Connexion en tant que"}:
        for spec in catalog.logout_actions:
            if spec.action == "SSO Disconnect":
                return spec
    for spec in catalog.logout_actions:
        if spec.action == "Déconnexion":
            return spec
    return rng.choice(catalog.logout_actions)


def build_normal_session(catalog: Catalog, user: UserProfile, session_start: datetime, rng: random.Random) -> List[EventPlan]:
    auth_specs = choose_auth_variant(catalog, rng)
    logout_spec = choose_logout(catalog, auth_specs, rng)
    route_weights = route_weights_for_catalog(catalog)
    business_route = weighted_choice(route_weights, rng)
    business_actions = catalog.route_actions.get(business_route, [])
    if not business_actions:
        # fallback to any tracked route
        fallback_route, _ = route_weights[0]
        business_route = fallback_route
        business_actions = catalog.route_actions.get(fallback_route, [])

    steps = rng.randint(1, min(4, max(1, len(business_actions))))
    chosen_actions = [rng.choice(business_actions) for _ in range(steps)]

    plans: List[EventPlan] = []
    current = session_start
    current_state = "login"
    for spec in auth_specs:
        state = "mfa" if spec.route in {"mfa", "mfa_email_list"} else "login"
        plans.append(EventPlan(spec=spec, created_at=current, route=spec.route, state=state))
        current += timedelta(seconds=rng.randint(6, 35))
        current_state = "home"
    # optional gates once per first connection-ish session
    if user.session_counter == 1 and rng.random() < 0.25:
        for gate_route in ["validate_legal_pages", "validate_info_dialog"]:
            gate_actions = catalog.route_actions.get(gate_route, [])
            if gate_actions:
                gate_spec = rng.choice(gate_actions)
                plans.append(EventPlan(spec=gate_spec, created_at=current, route=gate_route, state=gate_route))
                current += timedelta(seconds=rng.randint(5, 20))
    for spec in chosen_actions:
        plans.append(EventPlan(spec=spec, created_at=current, route=business_route, state=business_route))
        current += timedelta(seconds=rng.randint(8, 180))
    plans.append(EventPlan(spec=logout_spec, created_at=current, route="logout", state="logout"))
    return plans


def clone_plans(plans: Sequence[EventPlan]) -> List[EventPlan]:
    return [EventPlan(spec=p.spec, created_at=p.created_at, route=p.route, state=p.state, force_status=p.force_status, force_http_code=p.force_http_code, force_ip=p.force_ip, force_device=p.force_device, force_user_agent=p.force_user_agent, campaign_id=p.campaign_id, metadata=dict(p.metadata)) for p in plans]


def build_anomaly_session(catalog: Catalog, user: UserProfile, session_start: datetime, rng: random.Random, anomaly_type: str, shared_attack_ip: Optional[str] = None) -> List[EventPlan]:
    campaign_id = f"cmp-{anomaly_type}-{rng.randint(100,999)}"
    base = build_normal_session(catalog, user, session_start, rng)
    plans = clone_plans(base)
    for p in plans:
        p.campaign_id = campaign_id

    if anomaly_type == "skip_login":
        business_only = [p for p in plans if p.route not in {"login", "mfa", "mfa_email_list"}]
        return business_only or plans[1:]

    if anomaly_type == "repeated_fail":
        for p in plans:
            if p.route not in {"logout", "login", "mfa", "mfa_email_list"}:
                p.force_status = "KO"
                p.force_http_code = rng.choice([409, 422])
        return plans

    if anomaly_type == "rapid_fire":
        start = plans[0].created_at
        for i, p in enumerate(plans):
            p.created_at = start + timedelta(seconds=i)
        return plans

    if anomaly_type == "unusual_hour":
        weird = session_start.replace(hour=rng.choice([1, 2, 3, 4]), minute=rng.randint(0, 59), second=rng.randint(0, 59))
        for i, p in enumerate(plans):
            p.created_at = weird + timedelta(seconds=20 * i)
        return plans

    if anomaly_type == "geo_jump":
        other_cc = rng.choice([cc for cc in GEO_PROFILE.keys() if cc != user.country_code])
        other_prefix = rng.choice(GEO_PROFILE[other_cc]["prefixes"])
        jump_ip = random_public_ip(other_prefix, rng)
        if len(plans) >= 2:
            plans[1].force_ip = jump_ip
        if len(plans) >= 3:
            plans[2].force_ip = jump_ip
        return plans

    if anomaly_type == "impossible_device_switch":
        alt_device, alt_ua = rng.choice([d for d in DEVICE_POOL if d[0] != user.device])
        for p in plans[1:3]:
            p.force_device = alt_device
            p.force_user_agent = alt_ua
        return plans

    if anomaly_type == "ping_pong_loop":
        route_a = catalog.route_actions.get("refunds") or catalog.route_actions.get("documents") or []
        route_b = catalog.route_actions.get("tp_card") or catalog.route_actions.get("requests") or []
        auth = choose_auth_variant(catalog, rng)
        logout = choose_logout(catalog, auth, rng)
        current = session_start
        out: List[EventPlan] = []
        for spec in auth:
            out.append(EventPlan(spec=spec, created_at=current, route=spec.route, state=spec.route, campaign_id=campaign_id))
            current += timedelta(seconds=10)
        if route_a and route_b:
            a = rng.choice(route_a)
            b = rng.choice(route_b)
            for spec in [a, b, a, b, a, b]:
                out.append(EventPlan(spec=spec, created_at=current, route=spec.route, state=spec.route, campaign_id=campaign_id))
                current += timedelta(seconds=12)
        out.append(EventPlan(spec=logout, created_at=current, route="logout", state="logout", campaign_id=campaign_id))
        return out

    if anomaly_type == "data_exfiltration":
        download_pool = []
        for route, specs in catalog.route_actions.items():
            download_pool.extend([s for s in specs if s.is_download])
        if not download_pool:
            return plans
        auth = choose_auth_variant(catalog, rng)
        logout = choose_logout(catalog, auth, rng)
        current = session_start
        out: List[EventPlan] = []
        for spec in auth:
            out.append(EventPlan(spec=spec, created_at=current, route=spec.route, state=spec.route, campaign_id=campaign_id))
            current += timedelta(seconds=8)
        for _ in range(12):
            spec = rng.choice(download_pool)
            out.append(EventPlan(spec=spec, created_at=current, route=spec.route, state=spec.route, campaign_id=campaign_id))
            current += timedelta(seconds=8)
        out.append(EventPlan(spec=logout, created_at=current, route="logout", state="logout", campaign_id=campaign_id))
        return out

    if anomaly_type == "impossible_seq":
        # break the contract: logout first, then login, then duplicate login mid-session
        logout = choose_logout(catalog, [], rng)
        auth = choose_auth_variant(catalog, rng)
        business_route = next((route for route, actions in catalog.route_actions.items() if route not in {"logout", "login", "mfa", "mfa_email_list", "validate_legal_pages", "validate_info_dialog"} and actions), "refunds")
        business_spec = rng.choice(catalog.route_actions[business_route])
        current = session_start
        out = [EventPlan(spec=logout, created_at=current, route="logout", state="logout", campaign_id=campaign_id)]
        current += timedelta(seconds=5)
        out.append(EventPlan(spec=auth[0], created_at=current, route=auth[0].route, state=auth[0].route, campaign_id=campaign_id))
        current += timedelta(seconds=12)
        out.append(EventPlan(spec=business_spec, created_at=current, route=business_spec.route, state=business_spec.route, campaign_id=campaign_id))
        current += timedelta(seconds=4)
        out.append(EventPlan(spec=auth[0], created_at=current, route=auth[0].route, state=auth[0].route, campaign_id=campaign_id))
        current += timedelta(seconds=12)
        out.append(EventPlan(spec=choose_logout(catalog, auth, rng), created_at=current, route="logout", state="logout", campaign_id=campaign_id))
        return out

    if anomaly_type == "zombie_session":
        if len(plans) >= 3:
            plans[-1] = plans[-2]  # remove explicit logout by ending abruptly
            plans = plans[:-1]
            plans[-1].created_at = plans[0].created_at + timedelta(seconds=1300)
        return plans

    if anomaly_type == "distributed_brute_force":
        auth = catalog.auth_variants.get("direct", [[]])[0] if catalog.auth_variants.get("direct") else choose_auth_variant(catalog, rng)
        if not auth:
            return plans
        current = session_start
        attack_ip = shared_attack_ip or random_public_ip(("185", "220"), rng)
        out: List[EventPlan] = []
        for i in range(rng.randint(3, 6)):
            spec = auth[0]
            out.append(EventPlan(spec=spec, created_at=current, route=spec.route, state=spec.route, force_status="KO", force_http_code=rng.choice([401, 403]), force_ip=attack_ip, campaign_id=campaign_id, metadata={"attackCluster": "distributed_bruteforce"}))
            current += timedelta(seconds=rng.randint(1, 4))
        return out

    # fallback = normal session for unknown labels
    return plans


def materialize_session_events(user: UserProfile, plans: Sequence[EventPlan], session_id: str, session_number: int, anomaly_type: str, rng: random.Random) -> List[Dict[str, object]]:
    if not plans:
        return []
    session_start = plans[0].created_at
    session_end = plans[-1].created_at
    session_duration_seconds = max(0, int((session_end - session_start).total_seconds()))
    session_length = len(plans)

    unique_ips: set = set()
    unique_devices: set = set()
    cumulative_kos = 0
    longest_ko_streak = 0
    current_ko_streak = 0
    has_logged_in = 0
    download_actions_in_session = 0
    download_times: Deque[datetime] = deque()
    actions_so_far: List[str] = []

    initial_ip = plans[0].force_ip or user.ip
    initial_device = plans[0].force_device or user.device
    events: List[Dict[str, object]] = []

    for idx, plan in enumerate(plans):
        spec = plan.spec
        created_at = plan.created_at.astimezone(timezone.utc)
        prev_action = plans[idx - 1].spec.action if idx > 0 else ""
        next_action = plans[idx + 1].spec.action if idx < session_length - 1 else ""

        device = plan.force_device or user.device
        user_agent = plan.force_user_agent or user.user_agent
        ip = plan.force_ip or user.ip
        status = plan.force_status or choose_status(plan.route, rng)
        http_code = plan.force_http_code if plan.force_http_code is not None else choose_http_code(status, plan.route, spec.action, rng)

        unique_ips.add(ip)
        unique_devices.add(device)
        is_ip_changed = 1 if ip != initial_ip else 0
        is_device_changed = 1 if device != initial_device else 0

        if status == "KO":
            cumulative_kos += 1
            current_ko_streak += 1
            longest_ko_streak = max(longest_ko_streak, current_ko_streak)
        else:
            current_ko_streak = 0

        if is_login_action(spec.action):
            has_logged_in = 1

        is_download = 1 if spec.is_download else 0
        if is_download:
            download_actions_in_session += 1
            download_times.append(created_at)
        while download_times and (created_at - download_times[0]).total_seconds() > 120:
            download_times.popleft()
        downloads_last_2m = len(download_times)

        actions_so_far.append(spec.action)
        ping_pong_count = compute_ping_pong(actions_so_far)

        hour_of_day = created_at.hour
        day_of_week = created_at.weekday()
        is_weekend = 1 if day_of_week >= 5 else 0
        skip_login_flag = idx == 0 and not is_login_action(spec.action)
        unusual_hour = hour_of_day in {1, 2, 3, 4}
        rapid_fire_flag = idx > 0 and (created_at - plans[idx - 1].created_at).total_seconds() <= 1
        session_risk_score = compute_risk_score(is_ip_changed, is_device_changed, cumulative_kos, downloads_last_2m, ping_pong_count, unusual_hour, skip_login_flag, rapid_fire_flag)

        delta_since_last = 0 if idx == 0 else int((created_at - plans[idx - 1].created_at).total_seconds())

        event = {
            "id": str(uuid.uuid4()),
            "insuredId": user.insured_id,
            "status": status,
            "sessionId": session_id,
            "action": spec.action,
            "httpCode": http_code,
            "ip": ip,
            "userAgent": user_agent,
            "requestData": build_request_data(spec, user, rng, plan.metadata),
            "requestReturn": build_request_return(status, http_code, rng),
            "createdAt": iso_z(created_at),
            "type": spec.type_name,
            "environmentId": user.environment_id,
            "device": device,
            "persona": user.persona,
            "route": spec.route,
            "prevAction": prev_action,
            "nextAction": next_action,
            "companyIdList": [user.company_id],
            "companyGroupIdList": [user.company_group_id],
            "insurerIdList": [user.insurer_id],
            "companySectionIdList": [user.company_section_id],
            "insurerCodeIdList": [user.insurer_code_id],
            "healthcareNetworkIdList": [user.healthcare_network_id],
            "domainIdList": [user.domain_id],
            "subType": spec.sub_type,
            "countryCode": user.country_code,
            "city": user.city,
            "month": created_at.strftime("%Y-%m"),
            "sessionNumber": session_number,
            "sequenceInSession": idx + 1,
            "sessionLength": session_length,
            "sessionDurationSeconds": session_duration_seconds,
            "timeDeltaSinceLastAction": delta_since_last,
            "hourOfDay": hour_of_day,
            "dayOfWeek": day_of_week,
            "isWeekend": is_weekend,
            "isIpChanged": is_ip_changed,
            "uniqueIpsInSession": len(unique_ips),
            "cumulativeKOs": cumulative_kos,
            "longestKoStreak": longest_ko_streak,
            "hasLoggedIn": has_logged_in,
            "isDeviceChanged": is_device_changed,
            "uniqueDevicesInSession": len(unique_devices),
            "isDownloadAction": is_download,
            "downloadActionsInSession": download_actions_in_session,
            "downloadsLast2Minutes": downloads_last_2m,
            "pingPongCount": ping_pong_count,
            "sessionRiskScore": round(session_risk_score, 2),
            "is_anomaly": 1 if anomaly_type != "normal" else 0,
            "anomaly_type": anomaly_type,
            "campaignId": plan.campaign_id,
        }
        events.append(event)
    return events


def build_producer(args) -> "KafkaProducer":
    if KafkaProducer is None:
        raise RuntimeError("kafka-python is required. Install with: pip install kafka-python")
    return KafkaProducer(
        bootstrap_servers=[server.strip() for server in args.bootstrap_servers.split(",")],
        value_serializer=lambda value: json.dumps(value, ensure_ascii=False).encode("utf-8"),
        key_serializer=lambda value: value.encode("utf-8") if value else None,
        linger_ms=args.linger_ms,
        acks=args.acks,
        request_timeout_ms=args.request_timeout_ms,
        max_block_ms=args.max_block_ms,
        retries=args.retries,
    )


def close_producer(producer) -> None:
    if producer is None:
        return
    try:
        producer.flush(timeout=10)
    finally:
        try:
            producer.close(timeout=10)
        except Exception:
            pass


def emit_events(events: Sequence[Dict[str, object]], args, producer) -> int:
    sent = 0
    for event in events:
        if args.dry_run:
            print(json.dumps(event, ensure_ascii=False))
        else:
            future = producer.send(args.topic, key=event["insuredId"], value=event)
            if not args.async_send:
                metadata = future.get(timeout=max(1, args.request_timeout_ms // 1000))
                print(f"-> {metadata.topic}:{metadata.partition}@{metadata.offset} action={event['action']!r} anomaly={event['anomaly_type']}")
        sent += 1
        if args.rate > 0:
            time.sleep(max(0.0, 1.0 / args.rate))
    return sent


def parse_args(argv: Sequence[str]):
    p = argparse.ArgumentParser(description="JSON-driven Spring-Boot audit-trail Kafka simulator")
    p.add_argument("--bootstrap-servers", default=os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092"))
    p.add_argument("--topic", default=os.getenv("KAFKA_TOPIC", "topic-audit-trail"))
    p.add_argument("--backend-apis", default=str(DEFAULT_BACKEND_APIS))
    p.add_argument("--actions-order", default=str(DEFAULT_ACTIONS_ORDER))
    p.add_argument("--rate", type=float, default=4.0)
    p.add_argument("--duration", type=int, default=0)
    p.add_argument("--session-count", type=int, default=20)
    p.add_argument("--insured-count", type=int, default=12)
    p.add_argument("--seed", type=int, default=None)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--start-at", default="2025-01-01T08:00:00+00:00")
    p.add_argument("--normal-ratio", type=float, default=1.0)
    p.add_argument("--anomaly-type", default="auto", choices=["auto"] + ANOMALY_TYPES)
    p.add_argument("--linger-ms", type=int, default=0)
    p.add_argument("--acks", type=int, choices=[0, 1, -1], default=1)
    p.add_argument("--request-timeout-ms", type=int, default=10000)
    p.add_argument("--max-block-ms", type=int, default=10000)
    p.add_argument("--retries", type=int, default=0)
    p.add_argument("--async-send", action="store_true")
    return p.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)
    if args.session_count <= 0:
        print("--session-count must be > 0", file=sys.stderr)
        return 2
    if args.insured_count <= 0:
        print("--insured-count must be > 0", file=sys.stderr)
        return 2
    if not (0.0 <= args.normal_ratio <= 1.0):
        print("--normal-ratio must be between 0.0 and 1.0", file=sys.stderr)
        return 2

    rng = random.Random(args.seed)
    catalog = load_catalog(args.backend_apis, args.actions_order)
    users = build_users(rng, args.insured_count)
    cursor = parse_iso_dt(args.start_at)
    producer = None
    sessions_sent = 0
    events_sent = 0
    labels = Counter()
    start_wall = time.time()

    try:
        if not args.dry_run:
            producer = build_producer(args)

        while sessions_sent < args.session_count:
            if args.duration > 0 and (time.time() - start_wall) >= args.duration:
                break
            user = rng.choice(users)
            user.session_counter += 1
            session_id = f"{rng.randint(1000000, 9999999)}-{user.insured_id[-4:]}-{user.session_counter}"
            is_normal = rng.random() < args.normal_ratio
            if is_normal:
                label = "normal"
                plans = build_normal_session(catalog, user, cursor, rng)
            else:
                label = rng.choice(ANOMALY_TYPES) if args.anomaly_type == "auto" else args.anomaly_type
                plans = build_anomaly_session(catalog, user, cursor, rng, label)
            if plans:
                cursor = plans[-1].created_at + timedelta(seconds=rng.randint(20, 180))
            events = materialize_session_events(user, plans, session_id, user.session_counter, label, rng)
            events_sent += emit_events(events, args, producer)
            sessions_sent += 1
            labels[label] += 1

        print(json.dumps({
            "sessions_sent": sessions_sent,
            "events_sent": events_sent,
            "session_labels": dict(labels),
            "tracked_api_count": catalog.tracked_api_count,
            "untracked_api_count": catalog.untracked_api_count,
            "resolved_routes": {k: len(v) for k, v in catalog.route_actions.items()},
            "topic": args.topic,
            "dry_run": args.dry_run,
        }, ensure_ascii=False, indent=2), file=sys.stderr)
        return 0
    except KeyboardInterrupt:
        print("Stopped by user", file=sys.stderr)
        return 130
    finally:
        close_producer(producer)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
