// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_audio.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

/**
 * Protobuf enum {@code nvidia.riva.AudioEncoding}
 */
public enum AudioEncoding
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ENCODING_UNSPECIFIED = 0;</code>
   */
  ENCODING_UNSPECIFIED(0),
  /**
   * <code>LINEAR_PCM = 1;</code>
   */
  LINEAR_PCM(1),
  /**
   * <code>FLAC = 2;</code>
   */
  FLAC(2),
  /**
   * <code>MULAW = 3;</code>
   */
  MULAW(3),
  /**
   * <code>OGGOPUS = 4;</code>
   */
  OGGOPUS(4),
  /**
   * <code>ALAW = 20;</code>
   */
  ALAW(20),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ENCODING_UNSPECIFIED = 0;</code>
   */
  public static final int ENCODING_UNSPECIFIED_VALUE = 0;
  /**
   * <code>LINEAR_PCM = 1;</code>
   */
  public static final int LINEAR_PCM_VALUE = 1;
  /**
   * <code>FLAC = 2;</code>
   */
  public static final int FLAC_VALUE = 2;
  /**
   * <code>MULAW = 3;</code>
   */
  public static final int MULAW_VALUE = 3;
  /**
   * <code>OGGOPUS = 4;</code>
   */
  public static final int OGGOPUS_VALUE = 4;
  /**
   * <code>ALAW = 20;</code>
   */
  public static final int ALAW_VALUE = 20;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AudioEncoding valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AudioEncoding forNumber(int value) {
    switch (value) {
      case 0: return ENCODING_UNSPECIFIED;
      case 1: return LINEAR_PCM;
      case 2: return FLAC;
      case 3: return MULAW;
      case 4: return OGGOPUS;
      case 20: return ALAW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AudioEncoding>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AudioEncoding> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AudioEncoding>() {
          public AudioEncoding findValueByNumber(int number) {
            return AudioEncoding.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.neo.dashboard.asr.riva.proto.RivaAudio.getDescriptor().getEnumTypes().get(0);
  }

  private static final AudioEncoding[] VALUES = values();

  public static AudioEncoding valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AudioEncoding(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:nvidia.riva.AudioEncoding)
}

