// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

/**
 * Protobuf type {@code nvidia.riva.asr.EndpointingConfig}
 */
public final class EndpointingConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nvidia.riva.asr.EndpointingConfig)
    EndpointingConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EndpointingConfig.newBuilder() to construct.
  private EndpointingConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EndpointingConfig() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EndpointingConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_EndpointingConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_EndpointingConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.neo.dashboard.asr.riva.proto.EndpointingConfig.class, com.neo.dashboard.asr.riva.proto.EndpointingConfig.Builder.class);
  }

  private int bitField0_;
  public static final int START_HISTORY_FIELD_NUMBER = 1;
  private int startHistory_ = 0;
  /**
   * <code>optional int32 start_history = 1;</code>
   * @return Whether the startHistory field is set.
   */
  @java.lang.Override
  public boolean hasStartHistory() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 start_history = 1;</code>
   * @return The startHistory.
   */
  @java.lang.Override
  public int getStartHistory() {
    return startHistory_;
  }

  public static final int START_THRESHOLD_FIELD_NUMBER = 2;
  private float startThreshold_ = 0F;
  /**
   * <code>optional float start_threshold = 2;</code>
   * @return Whether the startThreshold field is set.
   */
  @java.lang.Override
  public boolean hasStartThreshold() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional float start_threshold = 2;</code>
   * @return The startThreshold.
   */
  @java.lang.Override
  public float getStartThreshold() {
    return startThreshold_;
  }

  public static final int STOP_HISTORY_FIELD_NUMBER = 3;
  private int stopHistory_ = 0;
  /**
   * <code>optional int32 stop_history = 3;</code>
   * @return Whether the stopHistory field is set.
   */
  @java.lang.Override
  public boolean hasStopHistory() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 stop_history = 3;</code>
   * @return The stopHistory.
   */
  @java.lang.Override
  public int getStopHistory() {
    return stopHistory_;
  }

  public static final int STOP_THRESHOLD_FIELD_NUMBER = 4;
  private float stopThreshold_ = 0F;
  /**
   * <code>optional float stop_threshold = 4;</code>
   * @return Whether the stopThreshold field is set.
   */
  @java.lang.Override
  public boolean hasStopThreshold() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional float stop_threshold = 4;</code>
   * @return The stopThreshold.
   */
  @java.lang.Override
  public float getStopThreshold() {
    return stopThreshold_;
  }

  public static final int STOP_HISTORY_EOU_FIELD_NUMBER = 5;
  private int stopHistoryEou_ = 0;
  /**
   * <code>optional int32 stop_history_eou = 5;</code>
   * @return Whether the stopHistoryEou field is set.
   */
  @java.lang.Override
  public boolean hasStopHistoryEou() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 stop_history_eou = 5;</code>
   * @return The stopHistoryEou.
   */
  @java.lang.Override
  public int getStopHistoryEou() {
    return stopHistoryEou_;
  }

  public static final int STOP_THRESHOLD_EOU_FIELD_NUMBER = 6;
  private float stopThresholdEou_ = 0F;
  /**
   * <code>optional float stop_threshold_eou = 6;</code>
   * @return Whether the stopThresholdEou field is set.
   */
  @java.lang.Override
  public boolean hasStopThresholdEou() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional float stop_threshold_eou = 6;</code>
   * @return The stopThresholdEou.
   */
  @java.lang.Override
  public float getStopThresholdEou() {
    return stopThresholdEou_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, startHistory_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeFloat(2, startThreshold_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, stopHistory_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeFloat(4, stopThreshold_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, stopHistoryEou_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeFloat(6, stopThresholdEou_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, startHistory_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, startThreshold_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, stopHistory_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, stopThreshold_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, stopHistoryEou_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, stopThresholdEou_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.neo.dashboard.asr.riva.proto.EndpointingConfig)) {
      return super.equals(obj);
    }
    com.neo.dashboard.asr.riva.proto.EndpointingConfig other = (com.neo.dashboard.asr.riva.proto.EndpointingConfig) obj;

    if (hasStartHistory() != other.hasStartHistory()) return false;
    if (hasStartHistory()) {
      if (getStartHistory()
          != other.getStartHistory()) return false;
    }
    if (hasStartThreshold() != other.hasStartThreshold()) return false;
    if (hasStartThreshold()) {
      if (java.lang.Float.floatToIntBits(getStartThreshold())
          != java.lang.Float.floatToIntBits(
              other.getStartThreshold())) return false;
    }
    if (hasStopHistory() != other.hasStopHistory()) return false;
    if (hasStopHistory()) {
      if (getStopHistory()
          != other.getStopHistory()) return false;
    }
    if (hasStopThreshold() != other.hasStopThreshold()) return false;
    if (hasStopThreshold()) {
      if (java.lang.Float.floatToIntBits(getStopThreshold())
          != java.lang.Float.floatToIntBits(
              other.getStopThreshold())) return false;
    }
    if (hasStopHistoryEou() != other.hasStopHistoryEou()) return false;
    if (hasStopHistoryEou()) {
      if (getStopHistoryEou()
          != other.getStopHistoryEou()) return false;
    }
    if (hasStopThresholdEou() != other.hasStopThresholdEou()) return false;
    if (hasStopThresholdEou()) {
      if (java.lang.Float.floatToIntBits(getStopThresholdEou())
          != java.lang.Float.floatToIntBits(
              other.getStopThresholdEou())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartHistory()) {
      hash = (37 * hash) + START_HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getStartHistory();
    }
    if (hasStartThreshold()) {
      hash = (37 * hash) + START_THRESHOLD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStartThreshold());
    }
    if (hasStopHistory()) {
      hash = (37 * hash) + STOP_HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getStopHistory();
    }
    if (hasStopThreshold()) {
      hash = (37 * hash) + STOP_THRESHOLD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStopThreshold());
    }
    if (hasStopHistoryEou()) {
      hash = (37 * hash) + STOP_HISTORY_EOU_FIELD_NUMBER;
      hash = (53 * hash) + getStopHistoryEou();
    }
    if (hasStopThresholdEou()) {
      hash = (37 * hash) + STOP_THRESHOLD_EOU_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getStopThresholdEou());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.neo.dashboard.asr.riva.proto.EndpointingConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nvidia.riva.asr.EndpointingConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nvidia.riva.asr.EndpointingConfig)
      com.neo.dashboard.asr.riva.proto.EndpointingConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_EndpointingConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_EndpointingConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neo.dashboard.asr.riva.proto.EndpointingConfig.class, com.neo.dashboard.asr.riva.proto.EndpointingConfig.Builder.class);
    }

    // Construct using com.neo.dashboard.asr.riva.proto.EndpointingConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      startHistory_ = 0;
      startThreshold_ = 0F;
      stopHistory_ = 0;
      stopThreshold_ = 0F;
      stopHistoryEou_ = 0;
      stopThresholdEou_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_EndpointingConfig_descriptor;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.EndpointingConfig getDefaultInstanceForType() {
      return com.neo.dashboard.asr.riva.proto.EndpointingConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.EndpointingConfig build() {
      com.neo.dashboard.asr.riva.proto.EndpointingConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.EndpointingConfig buildPartial() {
      com.neo.dashboard.asr.riva.proto.EndpointingConfig result = new com.neo.dashboard.asr.riva.proto.EndpointingConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.neo.dashboard.asr.riva.proto.EndpointingConfig result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.startHistory_ = startHistory_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.startThreshold_ = startThreshold_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stopHistory_ = stopHistory_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.stopThreshold_ = stopThreshold_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.stopHistoryEou_ = stopHistoryEou_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.stopThresholdEou_ = stopThresholdEou_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.neo.dashboard.asr.riva.proto.EndpointingConfig) {
        return mergeFrom((com.neo.dashboard.asr.riva.proto.EndpointingConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.neo.dashboard.asr.riva.proto.EndpointingConfig other) {
      if (other == com.neo.dashboard.asr.riva.proto.EndpointingConfig.getDefaultInstance()) return this;
      if (other.hasStartHistory()) {
        setStartHistory(other.getStartHistory());
      }
      if (other.hasStartThreshold()) {
        setStartThreshold(other.getStartThreshold());
      }
      if (other.hasStopHistory()) {
        setStopHistory(other.getStopHistory());
      }
      if (other.hasStopThreshold()) {
        setStopThreshold(other.getStopThreshold());
      }
      if (other.hasStopHistoryEou()) {
        setStopHistoryEou(other.getStopHistoryEou());
      }
      if (other.hasStopThresholdEou()) {
        setStopThresholdEou(other.getStopThresholdEou());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              startHistory_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              startThreshold_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 24: {
              stopHistory_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 37: {
              stopThreshold_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 40: {
              stopHistoryEou_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 53: {
              stopThresholdEou_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int startHistory_ ;
    /**
     * <code>optional int32 start_history = 1;</code>
     * @return Whether the startHistory field is set.
     */
    @java.lang.Override
    public boolean hasStartHistory() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 start_history = 1;</code>
     * @return The startHistory.
     */
    @java.lang.Override
    public int getStartHistory() {
      return startHistory_;
    }
    /**
     * <code>optional int32 start_history = 1;</code>
     * @param value The startHistory to set.
     * @return This builder for chaining.
     */
    public Builder setStartHistory(int value) {

      startHistory_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 start_history = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartHistory() {
      bitField0_ = (bitField0_ & ~0x00000001);
      startHistory_ = 0;
      onChanged();
      return this;
    }

    private float startThreshold_ ;
    /**
     * <code>optional float start_threshold = 2;</code>
     * @return Whether the startThreshold field is set.
     */
    @java.lang.Override
    public boolean hasStartThreshold() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float start_threshold = 2;</code>
     * @return The startThreshold.
     */
    @java.lang.Override
    public float getStartThreshold() {
      return startThreshold_;
    }
    /**
     * <code>optional float start_threshold = 2;</code>
     * @param value The startThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setStartThreshold(float value) {

      startThreshold_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional float start_threshold = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartThreshold() {
      bitField0_ = (bitField0_ & ~0x00000002);
      startThreshold_ = 0F;
      onChanged();
      return this;
    }

    private int stopHistory_ ;
    /**
     * <code>optional int32 stop_history = 3;</code>
     * @return Whether the stopHistory field is set.
     */
    @java.lang.Override
    public boolean hasStopHistory() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 stop_history = 3;</code>
     * @return The stopHistory.
     */
    @java.lang.Override
    public int getStopHistory() {
      return stopHistory_;
    }
    /**
     * <code>optional int32 stop_history = 3;</code>
     * @param value The stopHistory to set.
     * @return This builder for chaining.
     */
    public Builder setStopHistory(int value) {

      stopHistory_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 stop_history = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStopHistory() {
      bitField0_ = (bitField0_ & ~0x00000004);
      stopHistory_ = 0;
      onChanged();
      return this;
    }

    private float stopThreshold_ ;
    /**
     * <code>optional float stop_threshold = 4;</code>
     * @return Whether the stopThreshold field is set.
     */
    @java.lang.Override
    public boolean hasStopThreshold() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional float stop_threshold = 4;</code>
     * @return The stopThreshold.
     */
    @java.lang.Override
    public float getStopThreshold() {
      return stopThreshold_;
    }
    /**
     * <code>optional float stop_threshold = 4;</code>
     * @param value The stopThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setStopThreshold(float value) {

      stopThreshold_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional float stop_threshold = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStopThreshold() {
      bitField0_ = (bitField0_ & ~0x00000008);
      stopThreshold_ = 0F;
      onChanged();
      return this;
    }

    private int stopHistoryEou_ ;
    /**
     * <code>optional int32 stop_history_eou = 5;</code>
     * @return Whether the stopHistoryEou field is set.
     */
    @java.lang.Override
    public boolean hasStopHistoryEou() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 stop_history_eou = 5;</code>
     * @return The stopHistoryEou.
     */
    @java.lang.Override
    public int getStopHistoryEou() {
      return stopHistoryEou_;
    }
    /**
     * <code>optional int32 stop_history_eou = 5;</code>
     * @param value The stopHistoryEou to set.
     * @return This builder for chaining.
     */
    public Builder setStopHistoryEou(int value) {

      stopHistoryEou_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 stop_history_eou = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStopHistoryEou() {
      bitField0_ = (bitField0_ & ~0x00000010);
      stopHistoryEou_ = 0;
      onChanged();
      return this;
    }

    private float stopThresholdEou_ ;
    /**
     * <code>optional float stop_threshold_eou = 6;</code>
     * @return Whether the stopThresholdEou field is set.
     */
    @java.lang.Override
    public boolean hasStopThresholdEou() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional float stop_threshold_eou = 6;</code>
     * @return The stopThresholdEou.
     */
    @java.lang.Override
    public float getStopThresholdEou() {
      return stopThresholdEou_;
    }
    /**
     * <code>optional float stop_threshold_eou = 6;</code>
     * @param value The stopThresholdEou to set.
     * @return This builder for chaining.
     */
    public Builder setStopThresholdEou(float value) {

      stopThresholdEou_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional float stop_threshold_eou = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStopThresholdEou() {
      bitField0_ = (bitField0_ & ~0x00000020);
      stopThresholdEou_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nvidia.riva.asr.EndpointingConfig)
  }

  // @@protoc_insertion_point(class_scope:nvidia.riva.asr.EndpointingConfig)
  private static final com.neo.dashboard.asr.riva.proto.EndpointingConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.neo.dashboard.asr.riva.proto.EndpointingConfig();
  }

  public static com.neo.dashboard.asr.riva.proto.EndpointingConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EndpointingConfig>
      PARSER = new com.google.protobuf.AbstractParser<EndpointingConfig>() {
    @java.lang.Override
    public EndpointingConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EndpointingConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EndpointingConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.EndpointingConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

