// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface EndpointingConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.EndpointingConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 start_history = 1;</code>
   * @return Whether the startHistory field is set.
   */
  boolean hasStartHistory();
  /**
   * <code>optional int32 start_history = 1;</code>
   * @return The startHistory.
   */
  int getStartHistory();

  /**
   * <code>optional float start_threshold = 2;</code>
   * @return Whether the startThreshold field is set.
   */
  boolean hasStartThreshold();
  /**
   * <code>optional float start_threshold = 2;</code>
   * @return The startThreshold.
   */
  float getStartThreshold();

  /**
   * <code>optional int32 stop_history = 3;</code>
   * @return Whether the stopHistory field is set.
   */
  boolean hasStopHistory();
  /**
   * <code>optional int32 stop_history = 3;</code>
   * @return The stopHistory.
   */
  int getStopHistory();

  /**
   * <code>optional float stop_threshold = 4;</code>
   * @return Whether the stopThreshold field is set.
   */
  boolean hasStopThreshold();
  /**
   * <code>optional float stop_threshold = 4;</code>
   * @return The stopThreshold.
   */
  float getStopThreshold();

  /**
   * <code>optional int32 stop_history_eou = 5;</code>
   * @return Whether the stopHistoryEou field is set.
   */
  boolean hasStopHistoryEou();
  /**
   * <code>optional int32 stop_history_eou = 5;</code>
   * @return The stopHistoryEou.
   */
  int getStopHistoryEou();

  /**
   * <code>optional float stop_threshold_eou = 6;</code>
   * @return Whether the stopThresholdEou field is set.
   */
  boolean hasStopThresholdEou();
  /**
   * <code>optional float stop_threshold_eou = 6;</code>
   * @return The stopThresholdEou.
   */
  float getStopThresholdEou();
}
