// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

/**
 * Protobuf type {@code nvidia.riva.asr.PipelineStates}
 */
public final class PipelineStates extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nvidia.riva.asr.PipelineStates)
    PipelineStatesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PipelineStates.newBuilder() to construct.
  private PipelineStates(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PipelineStates() {
    vadProbabilities_ = emptyFloatList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PipelineStates();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_PipelineStates_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_PipelineStates_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.neo.dashboard.asr.riva.proto.PipelineStates.class, com.neo.dashboard.asr.riva.proto.PipelineStates.Builder.class);
  }

  public static final int VAD_PROBABILITIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList vadProbabilities_ =
      emptyFloatList();
  /**
   * <code>repeated float vad_probabilities = 1;</code>
   * @return A list containing the vadProbabilities.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getVadProbabilitiesList() {
    return vadProbabilities_;
  }
  /**
   * <code>repeated float vad_probabilities = 1;</code>
   * @return The count of vadProbabilities.
   */
  public int getVadProbabilitiesCount() {
    return vadProbabilities_.size();
  }
  /**
   * <code>repeated float vad_probabilities = 1;</code>
   * @param index The index of the element to return.
   * @return The vadProbabilities at the given index.
   */
  public float getVadProbabilities(int index) {
    return vadProbabilities_.getFloat(index);
  }
  private int vadProbabilitiesMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getVadProbabilitiesList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(vadProbabilitiesMemoizedSerializedSize);
    }
    for (int i = 0; i < vadProbabilities_.size(); i++) {
      output.writeFloatNoTag(vadProbabilities_.getFloat(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 4 * getVadProbabilitiesList().size();
      size += dataSize;
      if (!getVadProbabilitiesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      vadProbabilitiesMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.neo.dashboard.asr.riva.proto.PipelineStates)) {
      return super.equals(obj);
    }
    com.neo.dashboard.asr.riva.proto.PipelineStates other = (com.neo.dashboard.asr.riva.proto.PipelineStates) obj;

    if (!getVadProbabilitiesList()
        .equals(other.getVadProbabilitiesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVadProbabilitiesCount() > 0) {
      hash = (37 * hash) + VAD_PROBABILITIES_FIELD_NUMBER;
      hash = (53 * hash) + getVadProbabilitiesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.PipelineStates parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.neo.dashboard.asr.riva.proto.PipelineStates prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nvidia.riva.asr.PipelineStates}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nvidia.riva.asr.PipelineStates)
      com.neo.dashboard.asr.riva.proto.PipelineStatesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_PipelineStates_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_PipelineStates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neo.dashboard.asr.riva.proto.PipelineStates.class, com.neo.dashboard.asr.riva.proto.PipelineStates.Builder.class);
    }

    // Construct using com.neo.dashboard.asr.riva.proto.PipelineStates.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      vadProbabilities_ = emptyFloatList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_PipelineStates_descriptor;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.PipelineStates getDefaultInstanceForType() {
      return com.neo.dashboard.asr.riva.proto.PipelineStates.getDefaultInstance();
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.PipelineStates build() {
      com.neo.dashboard.asr.riva.proto.PipelineStates result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.PipelineStates buildPartial() {
      com.neo.dashboard.asr.riva.proto.PipelineStates result = new com.neo.dashboard.asr.riva.proto.PipelineStates(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.neo.dashboard.asr.riva.proto.PipelineStates result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        vadProbabilities_.makeImmutable();
        result.vadProbabilities_ = vadProbabilities_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.neo.dashboard.asr.riva.proto.PipelineStates) {
        return mergeFrom((com.neo.dashboard.asr.riva.proto.PipelineStates)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.neo.dashboard.asr.riva.proto.PipelineStates other) {
      if (other == com.neo.dashboard.asr.riva.proto.PipelineStates.getDefaultInstance()) return this;
      if (!other.vadProbabilities_.isEmpty()) {
        if (vadProbabilities_.isEmpty()) {
          vadProbabilities_ = other.vadProbabilities_;
          vadProbabilities_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureVadProbabilitiesIsMutable();
          vadProbabilities_.addAll(other.vadProbabilities_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              float v = input.readFloat();
              ensureVadProbabilitiesIsMutable();
              vadProbabilities_.addFloat(v);
              break;
            } // case 13
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureVadProbabilitiesIsMutable(alloc / 4);
              while (input.getBytesUntilLimit() > 0) {
                vadProbabilities_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.FloatList vadProbabilities_ = emptyFloatList();
    private void ensureVadProbabilitiesIsMutable() {
      if (!vadProbabilities_.isModifiable()) {
        vadProbabilities_ = makeMutableCopy(vadProbabilities_);
      }
      bitField0_ |= 0x00000001;
    }
    private void ensureVadProbabilitiesIsMutable(int capacity) {
      if (!vadProbabilities_.isModifiable()) {
        vadProbabilities_ = makeMutableCopy(vadProbabilities_, capacity);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated float vad_probabilities = 1;</code>
     * @return A list containing the vadProbabilities.
     */
    public java.util.List<java.lang.Float>
        getVadProbabilitiesList() {
      vadProbabilities_.makeImmutable();
      return vadProbabilities_;
    }
    /**
     * <code>repeated float vad_probabilities = 1;</code>
     * @return The count of vadProbabilities.
     */
    public int getVadProbabilitiesCount() {
      return vadProbabilities_.size();
    }
    /**
     * <code>repeated float vad_probabilities = 1;</code>
     * @param index The index of the element to return.
     * @return The vadProbabilities at the given index.
     */
    public float getVadProbabilities(int index) {
      return vadProbabilities_.getFloat(index);
    }
    /**
     * <code>repeated float vad_probabilities = 1;</code>
     * @param index The index to set the value at.
     * @param value The vadProbabilities to set.
     * @return This builder for chaining.
     */
    public Builder setVadProbabilities(
        int index, float value) {

      ensureVadProbabilitiesIsMutable();
      vadProbabilities_.setFloat(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float vad_probabilities = 1;</code>
     * @param value The vadProbabilities to add.
     * @return This builder for chaining.
     */
    public Builder addVadProbabilities(float value) {

      ensureVadProbabilitiesIsMutable();
      vadProbabilities_.addFloat(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float vad_probabilities = 1;</code>
     * @param values The vadProbabilities to add.
     * @return This builder for chaining.
     */
    public Builder addAllVadProbabilities(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureVadProbabilitiesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, vadProbabilities_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float vad_probabilities = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVadProbabilities() {
      vadProbabilities_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nvidia.riva.asr.PipelineStates)
  }

  // @@protoc_insertion_point(class_scope:nvidia.riva.asr.PipelineStates)
  private static final com.neo.dashboard.asr.riva.proto.PipelineStates DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.neo.dashboard.asr.riva.proto.PipelineStates();
  }

  public static com.neo.dashboard.asr.riva.proto.PipelineStates getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PipelineStates>
      PARSER = new com.google.protobuf.AbstractParser<PipelineStates>() {
    @java.lang.Override
    public PipelineStates parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PipelineStates> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PipelineStates> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.PipelineStates getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

