// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

/**
 * Protobuf type {@code nvidia.riva.asr.RecognizeRequest}
 */
public final class RecognizeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nvidia.riva.asr.RecognizeRequest)
    RecognizeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecognizeRequest.newBuilder() to construct.
  private RecognizeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecognizeRequest() {
    audio_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RecognizeRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_RecognizeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_RecognizeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.neo.dashboard.asr.riva.proto.RecognizeRequest.class, com.neo.dashboard.asr.riva.proto.RecognizeRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CONFIG_FIELD_NUMBER = 1;
  private com.neo.dashboard.asr.riva.proto.RecognitionConfig config_;
  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   * @return The config.
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RecognitionConfig getConfig() {
    return config_ == null ? com.neo.dashboard.asr.riva.proto.RecognitionConfig.getDefaultInstance() : config_;
  }
  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RecognitionConfigOrBuilder getConfigOrBuilder() {
    return config_ == null ? com.neo.dashboard.asr.riva.proto.RecognitionConfig.getDefaultInstance() : config_;
  }

  public static final int AUDIO_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString audio_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes audio = 2;</code>
   * @return The audio.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAudio() {
    return audio_;
  }

  public static final int ID_FIELD_NUMBER = 100;
  private com.neo.dashboard.asr.riva.proto.RequestId id_;
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RequestId getId() {
    return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
  }
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder() {
    return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getConfig());
    }
    if (!audio_.isEmpty()) {
      output.writeBytes(2, audio_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(100, getId());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getConfig());
    }
    if (!audio_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, audio_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(100, getId());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.neo.dashboard.asr.riva.proto.RecognizeRequest)) {
      return super.equals(obj);
    }
    com.neo.dashboard.asr.riva.proto.RecognizeRequest other = (com.neo.dashboard.asr.riva.proto.RecognizeRequest) obj;

    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (!getAudio()
        .equals(other.getAudio())) return false;
    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    hash = (37 * hash) + AUDIO_FIELD_NUMBER;
    hash = (53 * hash) + getAudio().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.neo.dashboard.asr.riva.proto.RecognizeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nvidia.riva.asr.RecognizeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nvidia.riva.asr.RecognizeRequest)
      com.neo.dashboard.asr.riva.proto.RecognizeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_RecognizeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_RecognizeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neo.dashboard.asr.riva.proto.RecognizeRequest.class, com.neo.dashboard.asr.riva.proto.RecognizeRequest.Builder.class);
    }

    // Construct using com.neo.dashboard.asr.riva.proto.RecognizeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConfigFieldBuilder();
        getIdFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      audio_ = com.google.protobuf.ByteString.EMPTY;
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_RecognizeRequest_descriptor;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.RecognizeRequest getDefaultInstanceForType() {
      return com.neo.dashboard.asr.riva.proto.RecognizeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.RecognizeRequest build() {
      com.neo.dashboard.asr.riva.proto.RecognizeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.RecognizeRequest buildPartial() {
      com.neo.dashboard.asr.riva.proto.RecognizeRequest result = new com.neo.dashboard.asr.riva.proto.RecognizeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.neo.dashboard.asr.riva.proto.RecognizeRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.config_ = configBuilder_ == null
            ? config_
            : configBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.audio_ = audio_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.neo.dashboard.asr.riva.proto.RecognizeRequest) {
        return mergeFrom((com.neo.dashboard.asr.riva.proto.RecognizeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.neo.dashboard.asr.riva.proto.RecognizeRequest other) {
      if (other == com.neo.dashboard.asr.riva.proto.RecognizeRequest.getDefaultInstance()) return this;
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      if (other.getAudio() != com.google.protobuf.ByteString.EMPTY) {
        setAudio(other.getAudio());
      }
      if (other.hasId()) {
        mergeId(other.getId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              audio_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 802: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 802
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.neo.dashboard.asr.riva.proto.RecognitionConfig config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.RecognitionConfig, com.neo.dashboard.asr.riva.proto.RecognitionConfig.Builder, com.neo.dashboard.asr.riva.proto.RecognitionConfigOrBuilder> configBuilder_;
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     * @return The config.
     */
    public com.neo.dashboard.asr.riva.proto.RecognitionConfig getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? com.neo.dashboard.asr.riva.proto.RecognitionConfig.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     */
    public Builder setConfig(com.neo.dashboard.asr.riva.proto.RecognitionConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
      } else {
        configBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     */
    public Builder setConfig(
        com.neo.dashboard.asr.riva.proto.RecognitionConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     */
    public Builder mergeConfig(com.neo.dashboard.asr.riva.proto.RecognitionConfig value) {
      if (configBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          config_ != null &&
          config_ != com.neo.dashboard.asr.riva.proto.RecognitionConfig.getDefaultInstance()) {
          getConfigBuilder().mergeFrom(value);
        } else {
          config_ = value;
        }
      } else {
        configBuilder_.mergeFrom(value);
      }
      if (config_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     */
    public Builder clearConfig() {
      bitField0_ = (bitField0_ & ~0x00000001);
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.RecognitionConfig.Builder getConfigBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.RecognitionConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            com.neo.dashboard.asr.riva.proto.RecognitionConfig.getDefaultInstance() : config_;
      }
    }
    /**
     * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.RecognitionConfig, com.neo.dashboard.asr.riva.proto.RecognitionConfig.Builder, com.neo.dashboard.asr.riva.proto.RecognitionConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.neo.dashboard.asr.riva.proto.RecognitionConfig, com.neo.dashboard.asr.riva.proto.RecognitionConfig.Builder, com.neo.dashboard.asr.riva.proto.RecognitionConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }

    private com.google.protobuf.ByteString audio_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes audio = 2;</code>
     * @return The audio.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAudio() {
      return audio_;
    }
    /**
     * <code>bytes audio = 2;</code>
     * @param value The audio to set.
     * @return This builder for chaining.
     */
    public Builder setAudio(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      audio_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes audio = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudio() {
      bitField0_ = (bitField0_ & ~0x00000002);
      audio_ = getDefaultInstance().getAudio();
      onChanged();
      return this;
    }

    private com.neo.dashboard.asr.riva.proto.RequestId id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder> idBuilder_;
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     * @return The id.
     */
    public com.neo.dashboard.asr.riva.proto.RequestId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder setId(com.neo.dashboard.asr.riva.proto.RequestId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder setId(
        com.neo.dashboard.asr.riva.proto.RequestId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder mergeId(com.neo.dashboard.asr.riva.proto.RequestId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          id_ != null &&
          id_ != com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      if (id_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public com.neo.dashboard.asr.riva.proto.RequestId.Builder getIdBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nvidia.riva.asr.RecognizeRequest)
  }

  // @@protoc_insertion_point(class_scope:nvidia.riva.asr.RecognizeRequest)
  private static final com.neo.dashboard.asr.riva.proto.RecognizeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.neo.dashboard.asr.riva.proto.RecognizeRequest();
  }

  public static com.neo.dashboard.asr.riva.proto.RecognizeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecognizeRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecognizeRequest>() {
    @java.lang.Override
    public RecognizeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecognizeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecognizeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RecognizeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

