// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface RecognitionConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.RecognitionConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.nvidia.riva.AudioEncoding encoding = 1;</code>
   * @return The enum numeric value on the wire for encoding.
   */
  int getEncodingValue();
  /**
   * <code>.nvidia.riva.AudioEncoding encoding = 1;</code>
   * @return The encoding.
   */
  com.neo.dashboard.asr.riva.proto.AudioEncoding getEncoding();

  /**
   * <code>int32 sample_rate_hertz = 2;</code>
   * @return The sampleRateHertz.
   */
  int getSampleRateHertz();

  /**
   * <code>string language_code = 3;</code>
   * @return The languageCode.
   */
  java.lang.String getLanguageCode();
  /**
   * <code>string language_code = 3;</code>
   * @return The bytes for languageCode.
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();

  /**
   * <code>int32 max_alternatives = 4;</code>
   * @return The maxAlternatives.
   */
  int getMaxAlternatives();

  /**
   * <code>bool profanity_filter = 5;</code>
   * @return The profanityFilter.
   */
  boolean getProfanityFilter();

  /**
   * <code>repeated .nvidia.riva.asr.SpeechContext speech_contexts = 6;</code>
   */
  java.util.List<com.neo.dashboard.asr.riva.proto.SpeechContext> 
      getSpeechContextsList();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechContext speech_contexts = 6;</code>
   */
  com.neo.dashboard.asr.riva.proto.SpeechContext getSpeechContexts(int index);
  /**
   * <code>repeated .nvidia.riva.asr.SpeechContext speech_contexts = 6;</code>
   */
  int getSpeechContextsCount();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechContext speech_contexts = 6;</code>
   */
  java.util.List<? extends com.neo.dashboard.asr.riva.proto.SpeechContextOrBuilder> 
      getSpeechContextsOrBuilderList();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechContext speech_contexts = 6;</code>
   */
  com.neo.dashboard.asr.riva.proto.SpeechContextOrBuilder getSpeechContextsOrBuilder(
      int index);

  /**
   * <code>int32 audio_channel_count = 7;</code>
   * @return The audioChannelCount.
   */
  int getAudioChannelCount();

  /**
   * <code>bool enable_word_time_offsets = 8;</code>
   * @return The enableWordTimeOffsets.
   */
  boolean getEnableWordTimeOffsets();

  /**
   * <code>bool enable_automatic_punctuation = 11;</code>
   * @return The enableAutomaticPunctuation.
   */
  boolean getEnableAutomaticPunctuation();

  /**
   * <code>bool enable_separate_recognition_per_channel = 12;</code>
   * @return The enableSeparateRecognitionPerChannel.
   */
  boolean getEnableSeparateRecognitionPerChannel();

  /**
   * <code>string model = 13;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 13;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>bool verbatim_transcripts = 14;</code>
   * @return The verbatimTranscripts.
   */
  boolean getVerbatimTranscripts();

  /**
   * <code>.nvidia.riva.asr.SpeakerDiarizationConfig diarization_config = 19;</code>
   * @return Whether the diarizationConfig field is set.
   */
  boolean hasDiarizationConfig();
  /**
   * <code>.nvidia.riva.asr.SpeakerDiarizationConfig diarization_config = 19;</code>
   * @return The diarizationConfig.
   */
  com.neo.dashboard.asr.riva.proto.SpeakerDiarizationConfig getDiarizationConfig();
  /**
   * <code>.nvidia.riva.asr.SpeakerDiarizationConfig diarization_config = 19;</code>
   */
  com.neo.dashboard.asr.riva.proto.SpeakerDiarizationConfigOrBuilder getDiarizationConfigOrBuilder();

  /**
   * <code>map&lt;string, string&gt; custom_configuration = 24;</code>
   */
  int getCustomConfigurationCount();
  /**
   * <code>map&lt;string, string&gt; custom_configuration = 24;</code>
   */
  boolean containsCustomConfiguration(
      java.lang.String key);
  /**
   * Use {@link #getCustomConfigurationMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getCustomConfiguration();
  /**
   * <code>map&lt;string, string&gt; custom_configuration = 24;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getCustomConfigurationMap();
  /**
   * <code>map&lt;string, string&gt; custom_configuration = 24;</code>
   */
  /* nullable */
java.lang.String getCustomConfigurationOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; custom_configuration = 24;</code>
   */
  java.lang.String getCustomConfigurationOrThrow(
      java.lang.String key);

  /**
   * <code>.nvidia.riva.asr.EndpointingConfig endpointing_config = 25;</code>
   * @return Whether the endpointingConfig field is set.
   */
  boolean hasEndpointingConfig();
  /**
   * <code>.nvidia.riva.asr.EndpointingConfig endpointing_config = 25;</code>
   * @return The endpointingConfig.
   */
  com.neo.dashboard.asr.riva.proto.EndpointingConfig getEndpointingConfig();
  /**
   * <code>.nvidia.riva.asr.EndpointingConfig endpointing_config = 25;</code>
   */
  com.neo.dashboard.asr.riva.proto.EndpointingConfigOrBuilder getEndpointingConfigOrBuilder();
}
