// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface RecognizeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.RecognizeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   * @return The config.
   */
  com.neo.dashboard.asr.riva.proto.RecognitionConfig getConfig();
  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   */
  com.neo.dashboard.asr.riva.proto.RecognitionConfigOrBuilder getConfigOrBuilder();

  /**
   * <code>bytes audio = 2;</code>
   * @return The audio.
   */
  com.google.protobuf.ByteString getAudio();

  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return The id.
   */
  com.neo.dashboard.asr.riva.proto.RequestId getId();
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   */
  com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder();
}
