// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface RecognizeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.RecognizeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionResult results = 1;</code>
   */
  java.util.List<com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult> 
      getResultsList();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionResult results = 1;</code>
   */
  com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult getResults(int index);
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionResult results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionResult results = 1;</code>
   */
  java.util.List<? extends com.neo.dashboard.asr.riva.proto.SpeechRecognitionResultOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionResult results = 1;</code>
   */
  com.neo.dashboard.asr.riva.proto.SpeechRecognitionResultOrBuilder getResultsOrBuilder(
      int index);

  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return The id.
   */
  com.neo.dashboard.asr.riva.proto.RequestId getId();
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   */
  com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder();
}
