// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_common.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface RequestIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.RequestId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
