// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_common.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public final class RivaCommon {
  private RivaCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nvidia_riva_RequestId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nvidia_riva_RequestId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035nvidia/riva/riva_common.proto\022\013nvidia." +
      "riva\"\032\n\tRequestId\022\r\n\005value\030\001 \001(\tB$\n com." +
      "neo.dashboard.asr.riva.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nvidia_riva_RequestId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nvidia_riva_RequestId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nvidia_riva_RequestId_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
