// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_audio.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public final class RivaAudio {
  private RivaAudio() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034nvidia/riva/riva_audio.proto\022\013nvidia.r" +
      "iva*e\n\rAudioEncoding\022\030\n\024ENCODING_UNSPECI" +
      "FIED\020\000\022\016\n\nLINEAR_PCM\020\001\022\010\n\004FLAC\020\002\022\t\n\005MULA" +
      "W\020\003\022\013\n\007OGGOPUS\020\004\022\010\n\004ALAW\020\024B$\n com.neo.da" +
      "shboard.asr.riva.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
