// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface SpeakerDiarizationConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.SpeakerDiarizationConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enable_speaker_diarization = 1;</code>
   * @return The enableSpeakerDiarization.
   */
  boolean getEnableSpeakerDiarization();

  /**
   * <code>int32 max_speaker_count = 2;</code>
   * @return The maxSpeakerCount.
   */
  int getMaxSpeakerCount();
}
