// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

/**
 * Protobuf type {@code nvidia.riva.asr.SpeechRecognitionResult}
 */
public final class SpeechRecognitionResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nvidia.riva.asr.SpeechRecognitionResult)
    SpeechRecognitionResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpeechRecognitionResult.newBuilder() to construct.
  private SpeechRecognitionResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpeechRecognitionResult() {
    alternatives_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpeechRecognitionResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_SpeechRecognitionResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_SpeechRecognitionResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult.class, com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult.Builder.class);
  }

  public static final int ALTERNATIVES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative> alternatives_;
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative> getAlternativesList() {
    return alternatives_;
  }
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder> 
      getAlternativesOrBuilderList() {
    return alternatives_;
  }
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  @java.lang.Override
  public int getAlternativesCount() {
    return alternatives_.size();
  }
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative getAlternatives(int index) {
    return alternatives_.get(index);
  }
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder getAlternativesOrBuilder(
      int index) {
    return alternatives_.get(index);
  }

  public static final int CHANNEL_TAG_FIELD_NUMBER = 2;
  private int channelTag_ = 0;
  /**
   * <code>int32 channel_tag = 2;</code>
   * @return The channelTag.
   */
  @java.lang.Override
  public int getChannelTag() {
    return channelTag_;
  }

  public static final int AUDIO_PROCESSED_FIELD_NUMBER = 3;
  private float audioProcessed_ = 0F;
  /**
   * <code>float audio_processed = 3;</code>
   * @return The audioProcessed.
   */
  @java.lang.Override
  public float getAudioProcessed() {
    return audioProcessed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < alternatives_.size(); i++) {
      output.writeMessage(1, alternatives_.get(i));
    }
    if (channelTag_ != 0) {
      output.writeInt32(2, channelTag_);
    }
    if (java.lang.Float.floatToRawIntBits(audioProcessed_) != 0) {
      output.writeFloat(3, audioProcessed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < alternatives_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, alternatives_.get(i));
    }
    if (channelTag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, channelTag_);
    }
    if (java.lang.Float.floatToRawIntBits(audioProcessed_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, audioProcessed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult)) {
      return super.equals(obj);
    }
    com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult other = (com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult) obj;

    if (!getAlternativesList()
        .equals(other.getAlternativesList())) return false;
    if (getChannelTag()
        != other.getChannelTag()) return false;
    if (java.lang.Float.floatToIntBits(getAudioProcessed())
        != java.lang.Float.floatToIntBits(
            other.getAudioProcessed())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAlternativesCount() > 0) {
      hash = (37 * hash) + ALTERNATIVES_FIELD_NUMBER;
      hash = (53 * hash) + getAlternativesList().hashCode();
    }
    hash = (37 * hash) + CHANNEL_TAG_FIELD_NUMBER;
    hash = (53 * hash) + getChannelTag();
    hash = (37 * hash) + AUDIO_PROCESSED_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAudioProcessed());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nvidia.riva.asr.SpeechRecognitionResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nvidia.riva.asr.SpeechRecognitionResult)
      com.neo.dashboard.asr.riva.proto.SpeechRecognitionResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_SpeechRecognitionResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_SpeechRecognitionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult.class, com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult.Builder.class);
    }

    // Construct using com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (alternativesBuilder_ == null) {
        alternatives_ = java.util.Collections.emptyList();
      } else {
        alternatives_ = null;
        alternativesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      channelTag_ = 0;
      audioProcessed_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_SpeechRecognitionResult_descriptor;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult getDefaultInstanceForType() {
      return com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult build() {
      com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult buildPartial() {
      com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult result = new com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult result) {
      if (alternativesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          alternatives_ = java.util.Collections.unmodifiableList(alternatives_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.alternatives_ = alternatives_;
      } else {
        result.alternatives_ = alternativesBuilder_.build();
      }
    }

    private void buildPartial0(com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.channelTag_ = channelTag_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.audioProcessed_ = audioProcessed_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult) {
        return mergeFrom((com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult other) {
      if (other == com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult.getDefaultInstance()) return this;
      if (alternativesBuilder_ == null) {
        if (!other.alternatives_.isEmpty()) {
          if (alternatives_.isEmpty()) {
            alternatives_ = other.alternatives_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAlternativesIsMutable();
            alternatives_.addAll(other.alternatives_);
          }
          onChanged();
        }
      } else {
        if (!other.alternatives_.isEmpty()) {
          if (alternativesBuilder_.isEmpty()) {
            alternativesBuilder_.dispose();
            alternativesBuilder_ = null;
            alternatives_ = other.alternatives_;
            bitField0_ = (bitField0_ & ~0x00000001);
            alternativesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAlternativesFieldBuilder() : null;
          } else {
            alternativesBuilder_.addAllMessages(other.alternatives_);
          }
        }
      }
      if (other.getChannelTag() != 0) {
        setChannelTag(other.getChannelTag());
      }
      if (other.getAudioProcessed() != 0F) {
        setAudioProcessed(other.getAudioProcessed());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative m =
                  input.readMessage(
                      com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.parser(),
                      extensionRegistry);
              if (alternativesBuilder_ == null) {
                ensureAlternativesIsMutable();
                alternatives_.add(m);
              } else {
                alternativesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              channelTag_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 29: {
              audioProcessed_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative> alternatives_ =
      java.util.Collections.emptyList();
    private void ensureAlternativesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        alternatives_ = new java.util.ArrayList<com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative>(alternatives_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder> alternativesBuilder_;

    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public java.util.List<com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative> getAlternativesList() {
      if (alternativesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(alternatives_);
      } else {
        return alternativesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public int getAlternativesCount() {
      if (alternativesBuilder_ == null) {
        return alternatives_.size();
      } else {
        return alternativesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative getAlternatives(int index) {
      if (alternativesBuilder_ == null) {
        return alternatives_.get(index);
      } else {
        return alternativesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder setAlternatives(
        int index, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.set(index, value);
        onChanged();
      } else {
        alternativesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder setAlternatives(
        int index, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.set(index, builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAlternatives(com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.add(value);
        onChanged();
      } else {
        alternativesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        int index, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.add(index, value);
        onChanged();
      } else {
        alternativesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.add(builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        int index, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.add(index, builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAllAlternatives(
        java.lang.Iterable<? extends com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative> values) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alternatives_);
        onChanged();
      } else {
        alternativesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder clearAlternatives() {
      if (alternativesBuilder_ == null) {
        alternatives_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        alternativesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder removeAlternatives(int index) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.remove(index);
        onChanged();
      } else {
        alternativesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder getAlternativesBuilder(
        int index) {
      return getAlternativesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder getAlternativesOrBuilder(
        int index) {
      if (alternativesBuilder_ == null) {
        return alternatives_.get(index);  } else {
        return alternativesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public java.util.List<? extends com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder> 
         getAlternativesOrBuilderList() {
      if (alternativesBuilder_ != null) {
        return alternativesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(alternatives_);
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder addAlternativesBuilder() {
      return getAlternativesFieldBuilder().addBuilder(
          com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.getDefaultInstance());
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder addAlternativesBuilder(
        int index) {
      return getAlternativesFieldBuilder().addBuilder(
          index, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.getDefaultInstance());
    }
    /**
     * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public java.util.List<com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder> 
         getAlternativesBuilderList() {
      return getAlternativesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder> 
        getAlternativesFieldBuilder() {
      if (alternativesBuilder_ == null) {
        alternativesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative.Builder, com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder>(
                alternatives_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        alternatives_ = null;
      }
      return alternativesBuilder_;
    }

    private int channelTag_ ;
    /**
     * <code>int32 channel_tag = 2;</code>
     * @return The channelTag.
     */
    @java.lang.Override
    public int getChannelTag() {
      return channelTag_;
    }
    /**
     * <code>int32 channel_tag = 2;</code>
     * @param value The channelTag to set.
     * @return This builder for chaining.
     */
    public Builder setChannelTag(int value) {

      channelTag_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 channel_tag = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelTag() {
      bitField0_ = (bitField0_ & ~0x00000002);
      channelTag_ = 0;
      onChanged();
      return this;
    }

    private float audioProcessed_ ;
    /**
     * <code>float audio_processed = 3;</code>
     * @return The audioProcessed.
     */
    @java.lang.Override
    public float getAudioProcessed() {
      return audioProcessed_;
    }
    /**
     * <code>float audio_processed = 3;</code>
     * @param value The audioProcessed to set.
     * @return This builder for chaining.
     */
    public Builder setAudioProcessed(float value) {

      audioProcessed_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float audio_processed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudioProcessed() {
      bitField0_ = (bitField0_ & ~0x00000004);
      audioProcessed_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nvidia.riva.asr.SpeechRecognitionResult)
  }

  // @@protoc_insertion_point(class_scope:nvidia.riva.asr.SpeechRecognitionResult)
  private static final com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult();
  }

  public static com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpeechRecognitionResult>
      PARSER = new com.google.protobuf.AbstractParser<SpeechRecognitionResult>() {
    @java.lang.Override
    public SpeechRecognitionResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SpeechRecognitionResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpeechRecognitionResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.SpeechRecognitionResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

