// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface SpeechRecognitionResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.SpeechRecognitionResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  java.util.List<com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative> 
      getAlternativesList();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternative getAlternatives(int index);
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  int getAlternativesCount();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  java.util.List<? extends com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder> 
      getAlternativesOrBuilderList();
  /**
   * <code>repeated .nvidia.riva.asr.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  com.neo.dashboard.asr.riva.proto.SpeechRecognitionAlternativeOrBuilder getAlternativesOrBuilder(
      int index);

  /**
   * <code>int32 channel_tag = 2;</code>
   * @return The channelTag.
   */
  int getChannelTag();

  /**
   * <code>float audio_processed = 3;</code>
   * @return The audioProcessed.
   */
  float getAudioProcessed();
}
