// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface SpeechContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.SpeechContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string phrases = 1;</code>
   * @return A list containing the phrases.
   */
  java.util.List<java.lang.String>
      getPhrasesList();
  /**
   * <code>repeated string phrases = 1;</code>
   * @return The count of phrases.
   */
  int getPhrasesCount();
  /**
   * <code>repeated string phrases = 1;</code>
   * @param index The index of the element to return.
   * @return The phrases at the given index.
   */
  java.lang.String getPhrases(int index);
  /**
   * <code>repeated string phrases = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the phrases at the given index.
   */
  com.google.protobuf.ByteString
      getPhrasesBytes(int index);

  /**
   * <code>float boost = 4;</code>
   * @return The boost.
   */
  float getBoost();
}
