// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface SpeechRecognitionAlternativeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.SpeechRecognitionAlternative)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transcript = 1;</code>
   * @return The transcript.
   */
  java.lang.String getTranscript();
  /**
   * <code>string transcript = 1;</code>
   * @return The bytes for transcript.
   */
  com.google.protobuf.ByteString
      getTranscriptBytes();

  /**
   * <code>float confidence = 2;</code>
   * @return The confidence.
   */
  float getConfidence();

  /**
   * <code>repeated .nvidia.riva.asr.WordInfo words = 3;</code>
   */
  java.util.List<com.neo.dashboard.asr.riva.proto.WordInfo> 
      getWordsList();
  /**
   * <code>repeated .nvidia.riva.asr.WordInfo words = 3;</code>
   */
  com.neo.dashboard.asr.riva.proto.WordInfo getWords(int index);
  /**
   * <code>repeated .nvidia.riva.asr.WordInfo words = 3;</code>
   */
  int getWordsCount();
  /**
   * <code>repeated .nvidia.riva.asr.WordInfo words = 3;</code>
   */
  java.util.List<? extends com.neo.dashboard.asr.riva.proto.WordInfoOrBuilder> 
      getWordsOrBuilderList();
  /**
   * <code>repeated .nvidia.riva.asr.WordInfo words = 3;</code>
   */
  com.neo.dashboard.asr.riva.proto.WordInfoOrBuilder getWordsOrBuilder(
      int index);

  /**
   * <code>repeated string language_code = 4;</code>
   * @return A list containing the languageCode.
   */
  java.util.List<java.lang.String>
      getLanguageCodeList();
  /**
   * <code>repeated string language_code = 4;</code>
   * @return The count of languageCode.
   */
  int getLanguageCodeCount();
  /**
   * <code>repeated string language_code = 4;</code>
   * @param index The index of the element to return.
   * @return The languageCode at the given index.
   */
  java.lang.String getLanguageCode(int index);
  /**
   * <code>repeated string language_code = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the languageCode at the given index.
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes(int index);
}
