// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

/**
 * Protobuf type {@code nvidia.riva.asr.StreamingRecognizeResponse}
 */
public final class StreamingRecognizeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nvidia.riva.asr.StreamingRecognizeResponse)
    StreamingRecognizeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingRecognizeResponse.newBuilder() to construct.
  private StreamingRecognizeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingRecognizeResponse() {
    results_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamingRecognizeResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse.class, com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RESULTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult> results_;
  /**
   * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult> getResultsList() {
    return results_;
  }
  /**
   * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.neo.dashboard.asr.riva.proto.StreamingRecognitionResultOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
   */
  @java.lang.Override
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult getResults(int index) {
    return results_.get(index);
  }
  /**
   * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.StreamingRecognitionResultOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  public static final int ID_FIELD_NUMBER = 100;
  private com.neo.dashboard.asr.riva.proto.RequestId id_;
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RequestId getId() {
    return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
  }
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder() {
    return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(1, results_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(100, getId());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < results_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, results_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(100, getId());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse)) {
      return super.equals(obj);
    }
    com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse other = (com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse) obj;

    if (!getResultsList()
        .equals(other.getResultsList())) return false;
    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nvidia.riva.asr.StreamingRecognizeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nvidia.riva.asr.StreamingRecognizeResponse)
      com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse.class, com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse.Builder.class);
    }

    // Construct using com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultsFieldBuilder();
        getIdFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
      } else {
        results_ = null;
        resultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeResponse_descriptor;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse getDefaultInstanceForType() {
      return com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse build() {
      com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse buildPartial() {
      com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse result = new com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse result) {
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
    }

    private void buildPartial0(com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse) {
        return mergeFrom((com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse other) {
      if (other == com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse.getDefaultInstance()) return this;
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      if (other.hasId()) {
        mergeId(other.getId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult m =
                  input.readMessage(
                      com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.parser(),
                      extensionRegistry);
              if (resultsBuilder_ == null) {
                ensureResultsIsMutable();
                results_.add(m);
              } else {
                resultsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 802: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 802
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        results_ = new java.util.ArrayList<com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult>(results_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResultOrBuilder> resultsBuilder_;

    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public java.util.List<com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder setResults(
        int index, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder setResults(
        int index, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder addResults(com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder addResults(
        int index, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder addResults(
        com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder addResults(
        int index, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder getResultsBuilder(
        int index) {
      return getResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.StreamingRecognitionResultOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public java.util.List<? extends com.neo.dashboard.asr.riva.proto.StreamingRecognitionResultOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder addResultsBuilder() {
      return getResultsFieldBuilder().addBuilder(
          com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.getDefaultInstance());
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder addResultsBuilder(
        int index) {
      return getResultsFieldBuilder().addBuilder(
          index, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.getDefaultInstance());
    }
    /**
     * <code>repeated .nvidia.riva.asr.StreamingRecognitionResult results = 1;</code>
     */
    public java.util.List<com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder> 
         getResultsBuilderList() {
      return getResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResultOrBuilder> 
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResult.Builder, com.neo.dashboard.asr.riva.proto.StreamingRecognitionResultOrBuilder>(
                results_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }

    private com.neo.dashboard.asr.riva.proto.RequestId id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder> idBuilder_;
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     * @return The id.
     */
    public com.neo.dashboard.asr.riva.proto.RequestId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder setId(com.neo.dashboard.asr.riva.proto.RequestId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder setId(
        com.neo.dashboard.asr.riva.proto.RequestId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder mergeId(com.neo.dashboard.asr.riva.proto.RequestId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          id_ != null &&
          id_ != com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      if (id_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public com.neo.dashboard.asr.riva.proto.RequestId.Builder getIdBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nvidia.riva.asr.StreamingRecognizeResponse)
  }

  // @@protoc_insertion_point(class_scope:nvidia.riva.asr.StreamingRecognizeResponse)
  private static final com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse();
  }

  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingRecognizeResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamingRecognizeResponse>() {
    @java.lang.Override
    public StreamingRecognizeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamingRecognizeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamingRecognizeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.StreamingRecognizeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

