// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

/**
 * Protobuf type {@code nvidia.riva.asr.StreamingRecognizeRequest}
 */
public final class StreamingRecognizeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nvidia.riva.asr.StreamingRecognizeRequest)
    StreamingRecognizeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingRecognizeRequest.newBuilder() to construct.
  private StreamingRecognizeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingRecognizeRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamingRecognizeRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest.class, com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest.Builder.class);
  }

  private int bitField0_;
  private int streamingRequestCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object streamingRequest_;
  public enum StreamingRequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    STREAMING_CONFIG(1),
    AUDIO_CONTENT(2),
    STREAMINGREQUEST_NOT_SET(0);
    private final int value;
    private StreamingRequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StreamingRequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static StreamingRequestCase forNumber(int value) {
      switch (value) {
        case 1: return STREAMING_CONFIG;
        case 2: return AUDIO_CONTENT;
        case 0: return STREAMINGREQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public StreamingRequestCase
  getStreamingRequestCase() {
    return StreamingRequestCase.forNumber(
        streamingRequestCase_);
  }

  public static final int STREAMING_CONFIG_FIELD_NUMBER = 1;
  /**
   * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
   * @return Whether the streamingConfig field is set.
   */
  @java.lang.Override
  public boolean hasStreamingConfig() {
    return streamingRequestCase_ == 1;
  }
  /**
   * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
   * @return The streamingConfig.
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig getStreamingConfig() {
    if (streamingRequestCase_ == 1) {
       return (com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig) streamingRequest_;
    }
    return com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.getDefaultInstance();
  }
  /**
   * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfigOrBuilder getStreamingConfigOrBuilder() {
    if (streamingRequestCase_ == 1) {
       return (com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig) streamingRequest_;
    }
    return com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.getDefaultInstance();
  }

  public static final int AUDIO_CONTENT_FIELD_NUMBER = 2;
  /**
   * <code>bytes audio_content = 2;</code>
   * @return Whether the audioContent field is set.
   */
  @java.lang.Override
  public boolean hasAudioContent() {
    return streamingRequestCase_ == 2;
  }
  /**
   * <code>bytes audio_content = 2;</code>
   * @return The audioContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAudioContent() {
    if (streamingRequestCase_ == 2) {
      return (com.google.protobuf.ByteString) streamingRequest_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int ID_FIELD_NUMBER = 100;
  private com.neo.dashboard.asr.riva.proto.RequestId id_;
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RequestId getId() {
    return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
  }
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   */
  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder() {
    return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (streamingRequestCase_ == 1) {
      output.writeMessage(1, (com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig) streamingRequest_);
    }
    if (streamingRequestCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) streamingRequest_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(100, getId());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (streamingRequestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig) streamingRequest_);
    }
    if (streamingRequestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) streamingRequest_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(100, getId());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest)) {
      return super.equals(obj);
    }
    com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest other = (com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (!getStreamingRequestCase().equals(other.getStreamingRequestCase())) return false;
    switch (streamingRequestCase_) {
      case 1:
        if (!getStreamingConfig()
            .equals(other.getStreamingConfig())) return false;
        break;
      case 2:
        if (!getAudioContent()
            .equals(other.getAudioContent())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    switch (streamingRequestCase_) {
      case 1:
        hash = (37 * hash) + STREAMING_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getStreamingConfig().hashCode();
        break;
      case 2:
        hash = (37 * hash) + AUDIO_CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getAudioContent().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nvidia.riva.asr.StreamingRecognizeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nvidia.riva.asr.StreamingRecognizeRequest)
      com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest.class, com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest.Builder.class);
    }

    // Construct using com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIdFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (streamingConfigBuilder_ != null) {
        streamingConfigBuilder_.clear();
      }
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      streamingRequestCase_ = 0;
      streamingRequest_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.neo.dashboard.asr.riva.proto.RivaAsr.internal_static_nvidia_riva_asr_StreamingRecognizeRequest_descriptor;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest getDefaultInstanceForType() {
      return com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest build() {
      com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest buildPartial() {
      com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest result = new com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest result) {
      result.streamingRequestCase_ = streamingRequestCase_;
      result.streamingRequest_ = this.streamingRequest_;
      if (streamingRequestCase_ == 1 &&
          streamingConfigBuilder_ != null) {
        result.streamingRequest_ = streamingConfigBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest) {
        return mergeFrom((com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest other) {
      if (other == com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      switch (other.getStreamingRequestCase()) {
        case STREAMING_CONFIG: {
          mergeStreamingConfig(other.getStreamingConfig());
          break;
        }
        case AUDIO_CONTENT: {
          setAudioContent(other.getAudioContent());
          break;
        }
        case STREAMINGREQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStreamingConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              streamingRequestCase_ = 1;
              break;
            } // case 10
            case 18: {
              streamingRequest_ = input.readBytes();
              streamingRequestCase_ = 2;
              break;
            } // case 18
            case 802: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 802
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int streamingRequestCase_ = 0;
    private java.lang.Object streamingRequest_;
    public StreamingRequestCase
        getStreamingRequestCase() {
      return StreamingRequestCase.forNumber(
          streamingRequestCase_);
    }

    public Builder clearStreamingRequest() {
      streamingRequestCase_ = 0;
      streamingRequest_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig, com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.Builder, com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfigOrBuilder> streamingConfigBuilder_;
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     * @return Whether the streamingConfig field is set.
     */
    @java.lang.Override
    public boolean hasStreamingConfig() {
      return streamingRequestCase_ == 1;
    }
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     * @return The streamingConfig.
     */
    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig getStreamingConfig() {
      if (streamingConfigBuilder_ == null) {
        if (streamingRequestCase_ == 1) {
          return (com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig) streamingRequest_;
        }
        return com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.getDefaultInstance();
      } else {
        if (streamingRequestCase_ == 1) {
          return streamingConfigBuilder_.getMessage();
        }
        return com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     */
    public Builder setStreamingConfig(com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig value) {
      if (streamingConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        streamingRequest_ = value;
        onChanged();
      } else {
        streamingConfigBuilder_.setMessage(value);
      }
      streamingRequestCase_ = 1;
      return this;
    }
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     */
    public Builder setStreamingConfig(
        com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.Builder builderForValue) {
      if (streamingConfigBuilder_ == null) {
        streamingRequest_ = builderForValue.build();
        onChanged();
      } else {
        streamingConfigBuilder_.setMessage(builderForValue.build());
      }
      streamingRequestCase_ = 1;
      return this;
    }
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     */
    public Builder mergeStreamingConfig(com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig value) {
      if (streamingConfigBuilder_ == null) {
        if (streamingRequestCase_ == 1 &&
            streamingRequest_ != com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.getDefaultInstance()) {
          streamingRequest_ = com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.newBuilder((com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig) streamingRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          streamingRequest_ = value;
        }
        onChanged();
      } else {
        if (streamingRequestCase_ == 1) {
          streamingConfigBuilder_.mergeFrom(value);
        } else {
          streamingConfigBuilder_.setMessage(value);
        }
      }
      streamingRequestCase_ = 1;
      return this;
    }
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     */
    public Builder clearStreamingConfig() {
      if (streamingConfigBuilder_ == null) {
        if (streamingRequestCase_ == 1) {
          streamingRequestCase_ = 0;
          streamingRequest_ = null;
          onChanged();
        }
      } else {
        if (streamingRequestCase_ == 1) {
          streamingRequestCase_ = 0;
          streamingRequest_ = null;
        }
        streamingConfigBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     */
    public com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.Builder getStreamingConfigBuilder() {
      return getStreamingConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     */
    @java.lang.Override
    public com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfigOrBuilder getStreamingConfigOrBuilder() {
      if ((streamingRequestCase_ == 1) && (streamingConfigBuilder_ != null)) {
        return streamingConfigBuilder_.getMessageOrBuilder();
      } else {
        if (streamingRequestCase_ == 1) {
          return (com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig) streamingRequest_;
        }
        return com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig, com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.Builder, com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfigOrBuilder> 
        getStreamingConfigFieldBuilder() {
      if (streamingConfigBuilder_ == null) {
        if (!(streamingRequestCase_ == 1)) {
          streamingRequest_ = com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.getDefaultInstance();
        }
        streamingConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig, com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig.Builder, com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfigOrBuilder>(
                (com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig) streamingRequest_,
                getParentForChildren(),
                isClean());
        streamingRequest_ = null;
      }
      streamingRequestCase_ = 1;
      onChanged();
      return streamingConfigBuilder_;
    }

    /**
     * <code>bytes audio_content = 2;</code>
     * @return Whether the audioContent field is set.
     */
    public boolean hasAudioContent() {
      return streamingRequestCase_ == 2;
    }
    /**
     * <code>bytes audio_content = 2;</code>
     * @return The audioContent.
     */
    public com.google.protobuf.ByteString getAudioContent() {
      if (streamingRequestCase_ == 2) {
        return (com.google.protobuf.ByteString) streamingRequest_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes audio_content = 2;</code>
     * @param value The audioContent to set.
     * @return This builder for chaining.
     */
    public Builder setAudioContent(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      streamingRequestCase_ = 2;
      streamingRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes audio_content = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudioContent() {
      if (streamingRequestCase_ == 2) {
        streamingRequestCase_ = 0;
        streamingRequest_ = null;
        onChanged();
      }
      return this;
    }

    private com.neo.dashboard.asr.riva.proto.RequestId id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder> idBuilder_;
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     * @return The id.
     */
    public com.neo.dashboard.asr.riva.proto.RequestId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder setId(com.neo.dashboard.asr.riva.proto.RequestId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder setId(
        com.neo.dashboard.asr.riva.proto.RequestId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder mergeId(com.neo.dashboard.asr.riva.proto.RequestId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          id_ != null &&
          id_ != com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      if (id_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public com.neo.dashboard.asr.riva.proto.RequestId.Builder getIdBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    public com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.neo.dashboard.asr.riva.proto.RequestId.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.nvidia.riva.RequestId id = 100;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.neo.dashboard.asr.riva.proto.RequestId, com.neo.dashboard.asr.riva.proto.RequestId.Builder, com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nvidia.riva.asr.StreamingRecognizeRequest)
  }

  // @@protoc_insertion_point(class_scope:nvidia.riva.asr.StreamingRecognizeRequest)
  private static final com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest();
  }

  public static com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingRecognizeRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamingRecognizeRequest>() {
    @java.lang.Override
    public StreamingRecognizeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamingRecognizeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamingRecognizeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

