// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface StreamingRecognitionConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.StreamingRecognitionConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   * @return The config.
   */
  com.neo.dashboard.asr.riva.proto.RecognitionConfig getConfig();
  /**
   * <code>.nvidia.riva.asr.RecognitionConfig config = 1;</code>
   */
  com.neo.dashboard.asr.riva.proto.RecognitionConfigOrBuilder getConfigOrBuilder();

  /**
   * <code>bool interim_results = 2;</code>
   * @return The interimResults.
   */
  boolean getInterimResults();
}
