// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface StreamingRecognizeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.StreamingRecognizeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
   * @return Whether the streamingConfig field is set.
   */
  boolean hasStreamingConfig();
  /**
   * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
   * @return The streamingConfig.
   */
  com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfig getStreamingConfig();
  /**
   * <code>.nvidia.riva.asr.StreamingRecognitionConfig streaming_config = 1;</code>
   */
  com.neo.dashboard.asr.riva.proto.StreamingRecognitionConfigOrBuilder getStreamingConfigOrBuilder();

  /**
   * <code>bytes audio_content = 2;</code>
   * @return Whether the audioContent field is set.
   */
  boolean hasAudioContent();
  /**
   * <code>bytes audio_content = 2;</code>
   * @return The audioContent.
   */
  com.google.protobuf.ByteString getAudioContent();

  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   * @return The id.
   */
  com.neo.dashboard.asr.riva.proto.RequestId getId();
  /**
   * <code>.nvidia.riva.RequestId id = 100;</code>
   */
  com.neo.dashboard.asr.riva.proto.RequestIdOrBuilder getIdOrBuilder();

  com.neo.dashboard.asr.riva.proto.StreamingRecognizeRequest.StreamingRequestCase getStreamingRequestCase();
}
