// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/riva/riva_asr.proto

// Protobuf Java Version: 3.25.6
package com.neo.dashboard.asr.riva.proto;

public interface WordInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nvidia.riva.asr.WordInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 start_time = 1;</code>
   * @return The startTime.
   */
  int getStartTime();

  /**
   * <code>int32 end_time = 2;</code>
   * @return The endTime.
   */
  int getEndTime();

  /**
   * <code>string word = 3;</code>
   * @return The word.
   */
  java.lang.String getWord();
  /**
   * <code>string word = 3;</code>
   * @return The bytes for word.
   */
  com.google.protobuf.ByteString
      getWordBytes();

  /**
   * <code>float confidence = 4;</code>
   * @return The confidence.
   */
  float getConfidence();

  /**
   * <code>int32 speaker_tag = 5;</code>
   * @return The speakerTag.
   */
  int getSpeakerTag();

  /**
   * <code>string language_code = 6;</code>
   * @return The languageCode.
   */
  java.lang.String getLanguageCode();
  /**
   * <code>string language_code = 6;</code>
   * @return The bytes for languageCode.
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();
}
