global:
  scrape_interval: 15s # Prometheus viendra aspirer les données toutes les 15 secondes

scrape_configs:
  - job_name: 'api-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # host.docker.internal permet à Docker de communiquer avec ton IntelliJ local !
      - targets: ['host.docker.internal:8081'] 

  - job_name: 'dataprocessor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Mets ici le port de ton dataprocessor