package com.neo.dashboard.dto.v36;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

/**
 * DTO carrying churn-prediction context for an insured user.
 * <p>
 * Wraps the probability, risk level, model identifiers, and any
 * feature-level warnings generated by the churn model.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class V36ChurnContextDto {
    /** Predicted churn probability (0.0 – 1.0). */
    @JsonAlias("churnProbability")
    private Double probability;
    /** Qualitative churn risk level derived from the probability. */
    @JsonAlias("churnRiskLevel")
    private String riskLevel;
    /** Name of the churn model that produced this prediction. */
    private String modelName;
    /** Artifact identifier or version of the deployed churn model. */
    private String modelArtifact;
    /** Feature-level warnings or anomalies detected by the churn model. */
    private Map<String, Object> featureWarnings;
}
