package com.neo.dashboard.dto.v36;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * DTO carrying forecast-prediction context for an alert/event.
 * <p>
 * Contains the predicted total events, anomaly rate, expected alert
 * volume, model identifiers, and any forecast-related warnings.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class V36ForecastContextDto {
    /** Predicted total number of events in the forecast window. */
    private Double predictedTotalEvents;
    /** Predicted anomaly rate (0.0 – 1.0) for the forecast window. */
    private Double predictedAnomalyRate;
    /** Expected volume of alerts in the forecast window. */
    private Double expectedAlertVolume;
    /** Map of forecast-model names to their artifact identifiers. */
    private Map<String, String> forecastModelNames;
    /** List of warnings generated by the forecast models. */
    private List<String> forecastWarnings;
    /** Raw forecast data as received from the prediction pipeline. */
    private Map<String, Object> raw;
}
