input {
  # 1. Écoute les logs venant de Spring Boot via TCP
  tcp {
    port => 5000
    codec => json_lines
    type => "springboot-logs"
  }
  
  # 2. Écoute les logs venant de ton Frontend Quasar via des requêtes HTTP POST
  http {
    port => 5001
    codec => json
    type => "quasar-frontend-logs"
    # --- LA MAGIE ANTI-CORS EST ICI ---
    response_headers => {
      "Access-Control-Allow-Origin" => "*"
      "Access-Control-Allow-Headers" => "Origin, X-Requested-With, Content-Type, Accept"
      "Access-Control-Allow-Methods" => "POST, OPTIONS"
    }
  }
}

filter {
  # C'est ici que tu pourras ajouter des règles plus tard (ex: extraire l'IP, parser des dates)
}

output {
  # Envoie tout vers Elasticsearch en créant des index séparés
  if [type] == "springboot-logs" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "spring-boot-logs-%{+YYYY.MM.dd}"
    }
  }
  else if [type] == "quasar-frontend-logs" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "quasar-logs-%{+YYYY.MM.dd}"
    }
  }
}